// Swiss railway stations and traffic points
// Source: https://data.sbb.ch/explore/dataset/dienststellen-gemass-opentransportdataswiss/
// Filter: TRAIN stops + traffic points with letter-only codes
export const STATIONEN: Record<string, string> = {
  'AA': 'Aarau',
  'AAGB': 'Aarau GB',
  'AARS': 'Aarwangen Schloss',
  'AARV': 'Aarwangen Vorstadt',
  'AARW': 'Aarwangen',
  'AAT': 'Aathal',
  'AB': 'Ausserberg',
  'ABE': 'Aarberg',
  'ABO': 'Aarburg-Oftringen',
  'ACLA': 'Acla da Fontauna',
  'AD': 'Aadorf',
  'ADF': 'Alpnach Dorf',
  'ADL': 'Adelrain (Abzw)',
  'ADW': 'Adliswil',
  'ADZ': 'Ardez',
  'AE': 'Aesch BL',
  'AEF': 'Aefligen',
  'AF': 'Affoltern am Albis',
  'AFWE': 'Affoltern-Weier',
  'AGHO': 'Aigle-Parc Aventure',
  'AGIP': 'Monthey Agip (embr)',
  'AGNO': 'Agno',
  'AHAU': 'Altishausen',
  'AI': 'Airolo',
  'AIG': 'Aigle',
  'AIGD': 'Aigle-Dépôt',
  'AIGM': 'Aigle-Place-du-Marché',
  'AIGT': 'Aigle-Château',
  'AL': 'Altdorf UR',
  'ALBE': 'Albeuve',
  'ALD': 'Luzern Allmend/Messe',
  'ALGR': 'Alp Grüm',
  'ALIL': 'Areuse Les Isles Littorail',
  'ALIT': 'Areuse Littorail',
  'ALL': 'Allaman',
  'ALLC': 'Alle Cargo Centre-Ajoie',
  'ALLE': 'Alle',
  'ALLI': 'Allières',
  'ALN': 'Altnau',
  'ALPS': 'Gonten Alpsteinblick',
  'ALRH': 'Altenrhein',
  'ALST': 'Altstätten Stadt',
  'ALT': 'Altstätten SG',
  'ALTD': 'Altendorf',
  'ALV': 'Alvaneu',
  'AN': 'Andelfingen',
  'AND': 'Andermatt',
  'AP': 'Ambrì-Piotta',
  'APPL': 'Apples',
  'APPZ': 'Appenzell',
  'ARB': 'Arbon',
  'ARBS': 'Arbon Seemoosriet',
  'ARCA': 'Archy A (bif)',
  'ARCH': 'Arch',
  'ARCY': 'Archy (bif)',
  'ARD': 'Ardon',
  'ARN': 'Arnegg',
  'ARNO': 'Les Arnoux',
  'AROS': 'Arosa',
  'ARVE': 'Arveyes',
  'ARZ': 'Arzier',
  'AS': 'Amsteg-Silenen',
  'ASGR': 'Amsteg Grund (Agl)',
  'ASNS': 'Assens',
  'ASSE': 'L\'Asse',
  'AST': 'Alpnachstad',
  'AT': 'Altmatt',
  'ATOR': 'Aarau Torfeld',
  'ATOS': 'Aareschlucht Ost (Bahn)',
  'ATTI': 'Attiswil',
  'AU': 'Au ZH',
  'AUSG': 'Au SG',
  'AUV': 'Auvernier',
  'AV': 'Avenches',
  'AVA': 'Les Avants',
  'AVIO': 'Les Aviolats',
  'AVLI': 'Auvernier Littorail',
  'AVRY': 'Avry-Matran',
  'AW': 'Amriswil',
  'AX': 'Arnex',
  'AZO': 'Alter Zoll',
  'BAA': 'Baar',
  'BAAL': 'Baar Lindenpark',
  'BAAN': 'Baar Neufeld',
  'BAD': 'Basel Bad Bf',
  'BADH': 'Basel Bad Rbf KH (Abzw)',
  'BAE': 'Bäch SZ',
  'BAER': 'Bärschwil',
  'BAET': 'Bäretswil Tobel (Agl)',
  'BAEW': 'Bäretswil',
  'BAL': 'Balerna',
  'BALL': 'Ballens',
  'BAN': 'Bannwil',
  'BARB': 'Gryon Barboleuse',
  'BASM': 'Balerna per Smistamento (bif)',
  'BASS': 'Bassins',
  'BAU': 'Baulmes',
  'BAV': 'Bavois',
  'BAZ': 'Bazenheid',
  'BAZZ': 'Bazenheid ZAB (Agl)',
  'BBK': 'Büron-Bad Knutwil',
  'BCHX': 'Bois-de-Chexbres',
  'BCT': 'Boncourt',
  'BD': 'Baden',
  'BDF': 'Burgdorf',
  'BDFB': 'Burgdorf Buchmatt',
  'BDFS': 'Burgdorf Steinhof',
  'BDO': 'Baden Oberstadt',
  'BDR': 'Boudry',
  'BDWE': 'Bei den Weihern',
  'BEAI': 'Bel-Air LEB',
  'BEBR': 'Bergün/Bravuogn',
  'BEDI': 'Bernina Diavolezza',
  'BEFR': 'Bergfrieden',
  'BEL': 'Bellinzona',
  'BELA': 'Bernina Lagalb',
  'BELE': 'Bellach Industrie',
  'BELL': 'Bellach',
  'BELV': 'Bellevue NE',
  'BEM': 'Le Bémont JU',
  'BEMG': 'Bettmeralp Talstation',
  'BEMM': 'Belmont-sur-Montreux',
  'BEND': 'Bendlehn',
  'BENS': 'Bossonnens',
  'BER': 'Berlingen',
  'BERB': 'Beringen Bad Bf',
  'BERC': 'Bercher',
  'BERD': 'Beringerfeld',
  'BERG': 'Berg',
  'BESU': 'Bernina Suot',
  'BET': 'Bettlach',
  'BEV': 'Bever',
  'BEVE': 'Zufikon Belvédère',
  'BEVI': 'Bévieux',
  'BEWI': 'Berikon-Widen',
  'BEX': 'Bex',
  'BEXM': 'Bex-Place-du-Marché',
  'BF': 'Belfaux CFF',
  'BFV': 'Belfaux-Village',
  'BG': 'Brugg AG',
  'BGBI': 'Bibenlos-Sonnenhof',
  'BGG': 'Brügg BE',
  'BGH': 'Burghalden',
  'BGIS': 'Bremgarten Isenlauf',
  'BGL': 'Bürglen TG',
  'BGOT': 'Bremgarten Obertor',
  'BGVL': 'Brugg AG VL',
  'BGW': 'Bremgarten West',
  'BH': 'Burgholz',
  'BHOF': 'Burghof',
  'BI': 'Biel/Bienne',
  'BIA': 'Biasca',
  'BIB': 'Biberbrugg',
  'BIBD': 'Biel/Bienne Bözingenfeld/Champ',
  'BIBS': 'Biberist RBS',
  'BICA': 'Bière-Casernes',
  'BIER': 'Bière',
  'BIG': 'Biglen',
  'BIGE': 'Bigenthal',
  'BIGG': 'Biberegg',
  'BIGO': 'Biel (Goms)',
  'BIHO': 'Binzenhof',
  'BIL': 'Bilten',
  'BIM': 'Biel Mett',
  'BIOG': 'Bioggio',
  'BIOM': 'Bioggio Molinazzo',
  'BIPO': 'Biel Produktionsanlage Ost',
  'BIR': 'Birmensdorf ZH',
  'BIRB': 'Biel/Bienne RB',
  'BIRI': 'Birmensdorf Industrie',
  'BIRR': 'Birr',
  'BIST': 'Biberist Ost',
  'BITS': 'Bitsch',
  'BK': 'Brenzikofen',
  'BKI': 'Bätterkinden',
  'BLB': 'Blankenburg',
  'BLG': 'Baldegg',
  'BLGK': 'Baldegg Kloster',
  'BLIT': 'Boudry Littorail',
  'BLIZ': 'Blitzingen',
  'BLL': 'Ballwil',
  'BLN': 'Bleien Liebegg',
  'BLON': 'Blonay',
  'BLU': 'Blumenau',
  'BMA': 'Bauma',
  'BN': 'Bern',
  'BNAS': 'Bern Europaplatz',
  'BNB': 'Bern Brünnen Westside',
  'BNBS': 'Bern Bümpliz Süd',
  'BNBZ': 'Bern Bümpliz Nord',
  'BNFE': 'Bern Felsenau',
  'BNFI': 'Bern Fischermätteli',
  'BNG': 'Bussnang',
  'BNK': 'Benken SG',
  'BNTI': 'Bern Tiefenau',
  'BNWD': 'Bern Wankdorf',
  'BNWE': 'Bern Weissenbühl',
  'BNWF': 'Bern Wylerfeld',
  'BNWM': 'Bern Weyermannshaus',
  'BNZ': 'Benzenschwil',
  'BO': 'Bodio TI',
  'BOBO': 'Bossy Bois (embr)',
  'BODE': 'Boden',
  'BOEC': 'Le Boéchet',
  'BOIS': 'Les Bois',
  'BOLE': 'Bôle',
  'BOLI': 'Bolligen',
  'BOLL': 'Bollement',
  'BOLT': 'Boltigen',
  'BOMO': 'Bossy Moulins (embr)',
  'BON': 'Bonstetten-Wettswil',
  'BONA': 'Bonaduz',
  'BONF': 'Bonfol',
  'BONI': 'Boniswil',
  'BOS': 'Boswil-Bünzen',
  'BOSS': 'Bossière',
  'BOT': 'Bottighofen',
  'BOU': 'Bouveret',
  'BOUQ': 'Bouquetins',
  'BOUT': 'Boll-Utzigen',
  'BOVE': 'Bovernier',
  'BOW': 'Bowil',
  'BP': 'Belp',
  'BPST': 'Belp Steinbach',
  'BR': 'Brig',
  'BRA': 'Le Brassus',
  'BRAG': 'Bad Ragaz',
  'BRBA': 'Basel SBB RB Gr A',
  'BREG': 'Bremgarten',
  'BREL': 'Les Breuleux-Eglise',
  'BREN': 'Les Brenets',
  'BREU': 'Les Breuleux',
  'BRFL': 'Brunnenfluh',
  'BRG': 'Bargen BE',
  'BRIN': 'La Brinaz',
  'BRIO': 'Brusio',
  'BRIT': 'Brittnau-Wikon',
  'BRMG': 'Brig Bahnhofplatz',
  'BRN': 'Brunnadern-Neckertal',
  'BRNI': 'Brunni',
  'BRO': 'Bronschhofen',
  'BROA': 'Bronschhofen AMP',
  'BROF': 'Broc-Chocolaterie',
  'BROV': 'Broc-Village',
  'BRRA': 'Brig Autoverlad',
  'BRT': 'Bretonnières',
  'BRU': 'Brunnen',
  'BRUE': 'Brünig-Hasliberg',
  'BRUT': 'Brüttelen',
  'BRW': 'Brienzwiler',
  'BRZ': 'Brienz',
  'BRZW': 'Brienz West',
  'BS': 'Basel SBB',
  'BSBH': 'Birsfelden Hafen',
  'BSC': 'Bassecourt',
  'BSD': 'Bassersdorf',
  'BSDH': 'Basel Dreispitz',
  'BSFR': 'Basel Grenze (FR)',
  'BSGB': 'Basel SBB GB',
  'BSII': 'Basel SBB RB II',
  'BSJA': 'Basel St. Jakob',
  'BSJH': 'Basel St. Johann Hafen',
  'BSKH': 'Basel Kleinhüningen Hafen',
  'BSNK': 'Basel SBB RB Nordkopf (Abzw)',
  'BSRB': 'Basel SBB RB',
  'BSSJ': 'Basel St. Johann',
  'BSVB': 'Basel VB Grenze',
  'BT': 'Buttes',
  'BTH': 'Balsthal',
  'BTUI': 'Boudry Tuilière',
  'BTW': 'Bettwiesen',
  'BU': 'Buchs SG',
  'BUAG': 'Buchs AG',
  'BUB': 'Bubikon',
  'BUC': 'Buckten',
  'BUD': 'Buchs-Dällikon',
  'BUDI': 'Buchs-Dällikon Industrie',
  'BUDZ': 'Burgau Deponie ZAB (Agl)',
  'BUE': 'Bülach',
  'BUEH': 'Bühler',
  'BUER': 'Büren an der Aare',
  'BUET': 'Bütschwil',
  'BUGN': 'Bugnei',
  'BUHA': 'Buchhalde (Spw)',
  'BUHO': 'Büren zum Hof',
  'BUL': 'Bulle',
  'BULI': 'Buchli',
  'BURE': 'Bure-Casernes',
  'BURG': 'Burglauenen',
  'BURI': 'Burier',
  'BURN': 'Buchrain',
  'BUS': 'Busswil BE',
  'BUSM': 'Bussy-Chardonney',
  'BUZE': 'Buchs SG Zement',
  'BV': 'Bevaix',
  'BW': 'Beinwil am See',
  'BWA': 'Burgistein',
  'BWL': 'Birrwil',
  'BWY': 'Bern Wyler',
  'BWYW': 'Bern Wyler West (Abzw)',
  'BX': 'Buix',
  'BXPN': 'Bex Pont-Neuf',
  'BY': 'Bussigny',
  'BZN': 'Bischofszell Nord',
  'BZS': 'Bischofszell Stadt',
  'CAAG': 'Cappella-Agnuzzo',
  'CABA': 'Lancy-Bachet',
  'CABM': 'Chamby-Musée',
  'CABV': 'Monthey Centre agr Bas-V (embr',
  'CABY': 'Chamby',
  'CADE': 'Cadera',
  'CAIO': 'Campascio',
  'CAME': 'Camedo',
  'CAMP': 'Campocologno',
  'CAP': 'Capolago-Riva S. Vitale',
  'CASE': 'Les Cases',
  'CASI': 'Castione Impianto d\'inversione',
  'CASL': 'Caslano',
  'CASR': 'Castrisch',
  'CAST': 'Castione-Arbedo',
  'CAVA': 'Cavaglia',
  'CAVI': 'Cavigliano',
  'CAZI': 'Cazis',
  'CBY': 'Collombey',
  'CC': 'Concise',
  'CCH': 'Courchavon',
  'CD': 'Cadenazzo',
  'CDM': 'Champ-du-Moulin',
  'CDUE': 'Cavadürli',
  'CEF': 'Cery-Fleur-de-Lys',
  'CELE': 'Celerina',
  'CELS': 'Celerina Staz',
  'CF': 'La Chaux-de-Fonds',
  'CFES': 'La Chaux-de-Fonds-Est',
  'CFG': 'La Chaux-de-Fonds-Grenier',
  'CFO': 'La Chaux-de-Fonds Les Forges',
  'CFV': 'Courfaivre',
  'CG': 'Courgenay',
  'CGE': 'Montreux-Collège',
  'CGY': 'Cugy FR',
  'CH': 'Chur',
  'CHA': 'Chamoson-St-Pierre-de-Clages',
  'CHAA': 'Cham Alpenblick',
  'CHAB': 'Le Châble VS',
  'CHAC': 'Chardonney-Château',
  'CHAL': 'Châtelard VD',
  'CHAM': 'Cham',
  'CHAN': 'Chantemerle-près-Blonay',
  'CHAR': 'Charrat-Fully',
  'CHAT': 'Châtillens',
  'CHAU': 'La Chaudanne-Les Moulins',
  'CHAY': 'En Charnet',
  'CHB': 'Les Charbonnières',
  'CHBL': 'Château-de-Blonay',
  'CHCO': 'Chaulin-Cornaux',
  'CHE': 'Chénens',
  'CHEB': 'Chêne-Bourg',
  'CHER': 'Chernex',
  'CHES': 'Cheseaux',
  'CHET': 'Le Locle Le Chalet',
  'CHEV': 'Les Chevalleyres',
  'CHF': 'Châteauneuf-Conthey',
  'CHFR': 'Le Châtelard-Frontière',
  'CHGB': 'Chur GB',
  'CHGI': 'Le Châtelard VS',
  'CHGN': 'Chigny',
  'CHHO': 'Genève-Champel',
  'CHI': 'Chiasso',
  'CHIZ': 'La Chiésaz',
  'CHMO': 'La Chèvrerie-Monterêt',
  'CHN': 'Chambrelien',
  'CHOE': 'Château-d\'Oex',
  'CHS': 'Cheyres',
  'CHSA': 'Chur Altstadt',
  'CHSD': 'Châtel-St-Denis',
  'CHSM': 'Chiasso Smistamento',
  'CHTV': 'Château-d\'Hauteville',
  'CHV': 'Chavornay',
  'CHVI': 'Chavornay-Industrie',
  'CHWE': 'Chur West',
  'CHWI': 'Chur Wiesental',
  'CHX': 'Chexbres-Village',
  'CHXA': 'La Chaux-d\'Abel',
  'CHXB': 'La Chaux-des-Breuleux',
  'CHY': 'Chambésy',
  'CHZ': 'Choindez',
  'CIB': 'La Cibourg',
  'CIN': 'Cinuos-chel-Brail',
  'CL': 'Clarens',
  'CLA': 'Claro',
  'CLAI': 'La Clairière',
  'CLB': 'Colombier NE',
  'CLME': 'Chez-le-Maître-Ecoles',
  'CN': 'Corcelles-Nord',
  'CNAL': 'Colombier NE Allées Littorail',
  'CNLC': 'Colombier NE Les Chézards',
  'CNLI': 'Colombier NE Littorail',
  'CO': 'Cortébert',
  'COBA': 'La Corbatière',
  'COED': 'Les Coeudres-Est',
  'COEU': 'Les Coeudres',
  'COG': 'Corgémont',
  'COI': 'Vernier',
  'COL': 'Le Locle-Col-des-Roches',
  'COLB': 'Col-de-Bretaye',
  'COLS': 'Col-de-Soud',
  'COMB': 'La Combe',
  'COMS': 'Les Combes',
  'COMU': 'Collombey-Village',
  'COP': 'Coppet',
  'COR': 'Corbier',
  'CORA': 'Corcapolo',
  'CORC': 'Corcelles BE',
  'CORM': 'Cormoret',
  'CORN': 'Cornaux NE',
  'CORS': 'Corseaux-Cornalles',
  'COS': 'Cossonay-Penthalaz',
  'COT': 'Cottens FR',
  'COTA': 'Combe-Tabeillon',
  'COTD': 'Cottendart (embr)',
  'COU': 'La Cour',
  'COUR': 'Courtepin',
  'COUS': 'Cousset',
  'CP': 'Corcelles-Peseux',
  'CR': 'Croy-Romainmôtier',
  'CREB': 'Le Creux-des-Biches',
  'CREM': 'Crémines',
  'CRET': 'Le Crêt-du-Locle',
  'CRFR': 'Cressier FR',
  'CRGD': 'Creux-de-Genthod',
  'CRNE': 'Cressier NE',
  'CRY': 'Champéry',
  'CRYV': 'Champéry-Village',
  'CS': 'Corcelles-Sud',
  'CT': 'Court',
  'CTM': 'Courtemaîche',
  'CTT': 'Courtételle',
  'CTY': 'Courtelary',
  'CU': 'Cully',
  'CURE': 'La Cure',
  'CURT': 'Li Curt',
  'CV': 'Convers',
  'CVN': 'La Conversion',
  'CVTR': 'Couvet',
  'CXN': 'Croix-du-Nant',
  'DA': 'Dachsen',
  'DAD': 'Davos Dorf',
  'DAF': 'Davos Frauenkirch',
  'DAG': 'Dagmersellen',
  'DAGL': 'Davos Glaris',
  'DAIL': 'Daillens',
  'DAKO': 'Davos Kongress/Eisstadion',
  'DAL': 'Dallenwil',
  'DALT': 'Davos Laret',
  'DAM': 'Davos Monstein',
  'DAV': 'Davos Platz',
  'DAW': 'Davos Wolfgang',
  'DAY': 'Le Day',
  'DE': 'Domat/Ems',
  'DEI': 'Deisswil',
  'DEN': 'Denges-Echandens',
  'DENB': 'Denges B (bif)',
  'DER': 'Derendingen',
  'DEU': 'Les Deurres',
  'DG': 'Degersheim',
  'DI': 'Dielsdorf',
  'DIAB': 'Les Diablerets',
  'DIBE': 'Distelberg',
  'DIE': 'Diepflingen',
  'DIEN': 'Dieni',
  'DIH': 'Dinhard',
  'DIS': 'Disentis/Mustér',
  'DK': 'Däniken SO',
  'DKRB': 'Däniken RB',
  'DMT': 'Delémont',
  'DN': 'Deitingen',
  'DOE': 'Döttingen',
  'DOM': 'Domdidier',
  'DON': 'Dotzigen',
  'DOP': 'Dompierre FR',
  'DOR': 'Dornach-Arlesheim',
  'DORF': 'Dorfnest (Abzw)',
  'DOT': 'Dottikon-Dintikon',
  'DOTU': 'Dottikon Umspannanlage',
  'DOUY': 'La Douay',
  'DR': 'Därstetten',
  'DROT': 'Dürrenroth',
  'DSB': 'Diesbach-Betschwanden',
  'DSH': 'Diessenhofen',
  'DSTO': 'Dietikon Stoffelbach',
  'DT': 'Dietikon',
  'DTF': 'Dietfurt',
  'DTL': 'Dietlikon',
  'DTSS': 'Dietikon Schöneggstrasse',
  'DU': 'Dulliken',
  'DUE': 'Dübendorf',
  'DUED': 'Düdingen',
  'DUG': 'Duggingen',
  'EB': 'Eggerberg',
  'EBG': 'Engelberg',
  'EBI': 'Ebikon',
  'EBIS': 'Erlenbach im Simmental',
  'EBLI': 'Ebligen',
  'EBR': 'Emmenbrücke',
  'ECH': 'Echallens',
  'ECHE': 'Les Echenards',
  'ECL': 'Eclépens',
  'ECLS': 'Eclépens sud',
  'ECU': 'Ecublens-Rue',
  'EDA': 'Ennenda',
  'EDR': 'Les Esserts-de-Rive',
  'EF': 'Effretikon',
  'EFG': 'Effingen',
  'EG': 'Egerkingen',
  'EGG': 'Egg',
  'EGL': 'Eglisau',
  'EGN': 'Egnach',
  'EI': 'Eiken',
  'EIF': 'Eifeld',
  'EIGE': 'Eigerwand',
  'EIIE': 'Ei im Emmental',
  'EIS': 'Einsiedeln',
  'EISM': 'Eismeer',
  'EK': 'Ebnat-Kappel',
  'EL': 'Elgg',
  'EMB': 'Embrach-Rorbas',
  'EMI': 'Les Emibois',
  'EMM': 'Emmenmatt',
  'EMMA': 'Emmat',
  'EMSW': 'Domat/Ems Werk',
  'ENGE': 'Enge im Simmental',
  'ENN': 'Enney',
  'ENT': 'Entlebuch',
  'EP': 'Ependes VD',
  'EPS': 'Epesses',
  'ER': 'Erstfeld',
  'ERDM': 'Erdmannlistein',
  'ERL': 'Erlen',
  'ERLB': 'Erlenbach ZH',
  'ERM': 'Ermatingen',
  'ESB': 'Eschenbach LU',
  'ESCH': 'Escholzmatt',
  'ESEE': 'Ermensee',
  'ESL': 'Eschlikon TG',
  'ESP': 'Essert-Pittet',
  'ESSC': 'Essert-sous-Champvent',
  'ESSL': 'Esslingen',
  'EST': 'Estavayer-le-Lac',
  'ETA': 'Etagnières',
  'ETH': 'Ettenhausen-Emmetschloo',
  'ETIE': 'Etiez',
  'ETOY': 'Etoy',
  'EV': 'Evionnaz',
  'EVOU': 'Les Evouettes',
  'EW': 'Etzwilen',
  'EWMA': 'Ewil Maxon',
  'EX': 'Exergillod',
  'EYHO': 'Eyholz',
  'EZ': 'Eschenz',
  'FA': 'Faido',
  'FAY': 'Fayaux',
  'FAYO': 'Fayot',
  'FB': 'Feldbach',
  'FBG': 'Felsberg',
  'FBO': 'Fangboden',
  'FBR': 'Fraubrunnen',
  'FCH': 'Forch',
  'FCK': 'Frick',
  'FE': 'Felsenau AG',
  'FEB': 'Felsenburg',
  'FEBR': 'Feldbrunnen',
  'FEG': 'Ferenbalm-Gurbrü',
  'FEL': 'Felben-Wellhausen',
  'FER': 'La Ferrière',
  'FET': 'Fehraltorf',
  'FETI': 'Fehraltorf Industrie',
  'FEY': 'Fey',
  'FF': 'Frauenfeld',
  'FFMA': 'Frauenfeld Marktplatz',
  'FFPP': 'Frauenfeld Paketpost',
  'FG': 'Faoug',
  'FI': 'Fischenthal',
  'FID': 'Fideris',
  'FIE': 'Fiesch',
  'FIED': 'Fiesch Feriendorf',
  'FILI': 'Filisur',
  'FIN': 'Finhaut',
  'FL': 'Flüelen',
  'FLA': 'Flawil',
  'FLE': 'Fleurier',
  'FLED': 'Flendruz',
  'FLLE': 'Les Fontanelles',
  'FLM': 'Flamatt',
  'FLMD': 'Flamatt Dorf',
  'FLUM': 'Flumenthal',
  'FMS': 'Flums',
  'FON': 'Fontanivent',
  'FONT': 'Fontannaz-Seulaz',
  'FR': 'Frutigen',
  'FRAE': 'Fräschels',
  'FRB': 'Freienbach SBB',
  'FRBS': 'Freienbach SOB',
  'FRD': 'Ballens-Froideville',
  'FRE': 'Frenkendorf-Füllinsdorf',
  'FREC': 'Frenkendorf-F. Containerdepot',
  'FRET': 'Les Frêtes',
  'FRI': 'Fribourg/Freiburg',
  'FRIB': 'Zürich Friesenberg',
  'FRIN': 'Frinvillier-Taubenloch',
  'FRNP': 'Frutigen Nordportal (Abzw)',
  'FRPO': 'Fribourg/Freiburg Poya',
  'FSMF': 'Faido SMF',
  'FT': 'Feuerthalen',
  'FTAN': 'Ftan Baraigla',
  'FTY': 'Fontanney',
  'FU': 'Full',
  'FUER': 'Fürgangen-Bellwald Talstation',
  'FUM': 'Les Fumeaux',
  'FURN': 'Furna',
  'FYDM': 'Foyer Dents-du-Midi',
  'GA': 'Gampel-Steg',
  'GAE': 'Gänsbrunnen',
  'GAIS': 'Gais',
  'GAMS': 'Gamsen SBB',
  'GAS': 'Gasel',
  'GBA': 'Griesbach',
  'GBSG': 'St. Gallen Güterbahnhof',
  'GD': 'Arth-Goldau',
  'GDA': 'Gordola',
  'GDBE': 'Genthod-Bellevue',
  'GE': 'Genève',
  'GEAP': 'Genève-Aéroport',
  'GEC': 'Les Geneveys-sur-Coffrane',
  'GELF': 'Gelfingen',
  'GEN': 'Genolier',
  'GEPR': 'Genève-La-Praille',
  'GER': 'Gerra (Gambarogno)',
  'GERO': 'Gerolfingen',
  'GES': 'Geschinen',
  'GESE': 'Genève-Sécheron',
  'GEST': 'Genève-Stade',
  'GET': 'Gettnau',
  'GETG': 'Gettnau Güteranlage',
  'GEUE': 'Geuensee',
  'GEV': 'Genève-Eaux-Vives',
  'GEXI': 'Gexi',
  'GF': 'Glattfelden',
  'GFEL': 'Gfeld',
  'GH': 'Grosshöchstetten',
  'GI': 'Giswil',
  'GIB': 'Gibswil',
  'GIDI': 'Giustizia (dira)',
  'GIOC': 'Giornico (c bin)',
  'GIOV': 'Monthey Giovanola (embr)',
  'GIU': 'Giubiasco',
  'GIV': 'Givisiez',
  'GIVI': 'Givrins',
  'GIVR': 'La Givrine',
  'GKD': 'Gelterkinden',
  'GL': 'Glarus',
  'GLA': 'Gland',
  'GLB': 'Glattbrugg',
  'GLF': 'Gerlafingen',
  'GLO': 'Glovelier',
  'GLUR': 'Gluringen',
  'GLZB': 'Glanzenberg',
  'GM': 'Granges-Marnand',
  'GMM': 'Gümmenen',
  'GMOU': 'Grand-Moulin',
  'GN': 'Grenchen Nord',
  'GO': 'Goppenstein',
  'GOAR': 'Goppenstein Autoverlad',
  'GOE': 'Göschenen',
  'GOL': 'Goldach',
  'GON': 'Gontenschwil',
  'GONB': 'Gontenbad',
  'GONT': 'Gonten',
  'GOR': 'Gorgier-St-Aubin',
  'GOT': 'La Gottaz',
  'GP': 'Gampelen',
  'GRAC': 'Les Granges-Gérignoz',
  'GRAE': 'Gränichen',
  'GRAF': 'Grafenort',
  'GRAO': 'Gränichen Oberdorf',
  'GRAT': 'Gränichen Töndler',
  'GRBG': 'Gryon Bois-Gentil',
  'GRCH': 'Gryon-Chalméry',
  'GREL': 'Grellingen',
  'GREN': 'Grengiols',
  'GRES': 'Grésaley',
  'GRF': 'Grüenfeld',
  'GRIN': 'Grindelwald',
  'GRMA': 'Grünenmatt',
  'GRO': 'Grolley',
  'GRRI': 'Grafenried',
  'GRS': 'Grandson',
  'GRU': 'Grubenwald',
  'GRUB': 'Gruben',
  'GRUS': 'Grüsch',
  'GRV': 'Grandvaux',
  'GRVI': 'Villars-sous-Mont',
  'GRY': 'Gruyères',
  'GRYO': 'Gryon',
  'GS': 'Grenchen Süd',
  'GSAG': 'Emmenbrücke Gersag',
  'GSK': 'Gisikon-Root',
  'GSS': 'Gossau SG',
  'GSSO': 'Gossau-Sommerau (Agl)',
  'GST': 'Gstaad',
  'GT': 'Gammenthal',
  'GU': 'Gurtnellen',
  'GUA': 'Guarda',
  'GUBU': 'Gutenburg',
  'GUE': 'Gümligen',
  'GUET': 'Güttingen',
  'GUN': 'Guntershausen',
  'GVAL': 'Grandval',
  'GW': 'Gwatt',
  'GZ': 'Galmiz',
  'HA': 'Hasle-Rüegsau',
  'HAE': 'Hägendorf',
  'HAEW': 'Häggenschwil-Winden',
  'HAG': 'Haag-Gams',
  'HALD': 'Haldenstein',
  'HAMO': 'Häusernmoos',
  'HAMU': 'Hard-Mumenthal',
  'HAS': 'Hasle LU',
  'HB': 'Herzogenbuchsee',
  'HBK': 'Hindelbank',
  'HBRG': 'Hebrig',
  'HBTN': 'Hauenstein Nord (Spw)',
  'HBTS': 'Hauenstein Süd (Spw)',
  'HD': 'Hallwil',
  'HDK': 'Hendschiken',
  'HE': 'Herisau',
  'HEBG': 'Heerbrugg',
  'HEBR': 'Herbriggen',
  'HECK': 'Hagneck',
  'HED': 'Hedingen',
  'HEI': 'Heiden',
  'HEIN': 'Widen Heinrüti',
  'HEM': 'Hemishofen',
  'HEN': 'Henniez',
  'HERB': 'Herblingen',
  'HERL': 'Herrliberg-Feldmeilen',
  'HET': 'Hettlingen',
  'HG': 'Horgen',
  'HGO': 'Horgen Oberdorf',
  'HGT': 'Henggart',
  'HGV': 'Les Hauts-Geneveys',
  'HGW': 'Hergiswil NW',
  'HI': 'Hinwil',
  'HIK': 'Hitzkirch',
  'HINT': 'Hinteregg',
  'HIRS': 'Hirschberg',
  'HIT': 'Hirschthal',
  'HM': 'Hüttlingen-Mettendorf',
  'HMB': 'Heimberg',
  'HN': 'Horn',
  'HNS': 'Hornussen',
  'HO': 'Hochdorf',
  'HOBK': 'Holderbank AG',
  'HOEB': 'Höcklerbrücke',
  'HOND': 'Hondrich Süd',
  'HOS': 'Hospental',
  'HOSA': 'Hochdorf Schönau',
  'HOT': 'Horchental',
  'HPT': 'Hauptwil',
  'HRK': 'Härkingen Post',
  'HT': 'Hohtenn',
  'HTV': 'Hauteville',
  'HU': 'Hunzenschwil',
  'HUCH': 'Hünenberg Chämleten',
  'HUE': 'Hüswil',
  'HUER': 'Hürlistein (Abzw)',
  'HUEW': 'Hüntwangen-Wil',
  'HUR': 'Hurden',
  'HUSW': 'Hüswil West',
  'HUZY': 'Hünenberg Zythus',
  'HW': 'Horw',
  'HWIL': 'Huttwil',
  'HWSZ': 'Huttwil Sportzentrum',
  'HZH': 'Holzhäusern',
  'IGIS': 'Igis',
  'IL': 'Illnau',
  'ILZ': 'Ilanz',
  'IM': 'Immensee',
  'IMHO': 'Im Holz',
  'INN': 'Innertkirchen Kraftwerk (Bahn)',
  'INNP': 'Innertkirchen Grimseltor',
  'INS': 'Ins',
  'INSD': 'Ins Dorf',
  'INTR': 'Intragna',
  'INUN': 'Innertkirchen Unterwasser',
  'IO': 'Interlaken Ost',
  'IP': 'Ipsach',
  'IPHE': 'Ipsach Herdi',
  'ISL': 'Islikon',
  'ISLE': 'L\'Isle',
  'IT': 'Itingen',
  'ITT': 'Ittigen bei Bern',
  'IW': 'Interlaken West',
  'JAK': 'Jakobsbad',
  'JAZ': 'Jenaz',
  'JEG': 'Jegenstorf',
  'JO': 'Jona',
  'JOCL': 'Genolier clinique/campus',
  'JON': 'Jonction (Genève)',
  'JOR': 'Jor',
  'JOUM': 'Jouxtens-Mézery',
  'JTAL': 'Jakobstal',
  'KA': 'Kandersteg',
  'KAAG': 'Kaiserstuhl AG',
  'KAB': 'Kaltbrunn',
  'KABO': 'Kaltenboden (Agl)',
  'KAEP': 'Chäppeli',
  'KAHE': 'Kaltenherberg',
  'KAI': 'Kaiserstuhl OW',
  'KAL': 'Kallnach',
  'KALP': 'Kalpetran',
  'KARA': 'Kandersteg Autoverlad',
  'KAU': 'Kaiseraugst',
  'KB': 'Koblenz',
  'KBD': 'Koblenz Dorf',
  'KD': 'Kaufdorf',
  'KDI': 'Kleindietwil',
  'KE': 'Kemptthal',
  'KF': 'Konolfingen',
  'KGD': 'Küngoldingen',
  'KGO': 'Küsnacht Goldbach',
  'KH': 'Krattighalde',
  'KHF': 'Kehlhof',
  'KI': 'Kiesen',
  'KIAL': 'Kirchberg-Alchenflüh',
  'KIL': 'Kilchberg ZH',
  'KK': 'Kölliken',
  'KKO': 'Kölliken Oberdorf',
  'KL': 'Kloten',
  'KLB': 'Kloten Balsberg',
  'KLI': 'Klingnau',
  'KLO': 'Klosters Platz',
  'KLOD': 'Klosters Dorf',
  'KLUS': 'Klus',
  'KLW': 'Killwangen-Spreitenbach',
  'KMUE': 'Zug Chollermüli',
  'KN': 'Kempten',
  'KNO': 'Knonau',
  'KOE': 'Köniz',
  'KOL': 'Kollbrunn',
  'KPT': 'Kempraten',
  'KR': 'Kreuzlingen',
  'KRA': 'Kradolf',
  'KRB': 'Kreuzlingen Bernrain',
  'KREU': 'Kreuzstrasse',
  'KRH': 'Kreuzlingen Hafen',
  'KRM': 'Kriens Mattenhof',
  'KRU': 'Krummenau',
  'KS': 'Kehrsatz',
  'KSMD': 'Kölliken Sondermülldeponie',
  'KSN': 'Kehrsatz Nord',
  'KUE': 'Küssnacht am Rigi',
  'KUEB': 'Küblis',
  'KUES': 'Küsnacht ZH',
  'KURZ': 'Kurzrickenbach Seepark',
  'KWL': 'Kesswil',
  'KZ': 'Kerzers',
  'KZPP': 'Kerzers Papiliorama',
  'LA': 'Lachen SZ',
  'LADO': 'Langendorf',
  'LAED': 'Lädeli',
  'LAFA': 'La Faverge',
  'LAL': 'Lally',
  'LAM': 'Lamone-Cadempino',
  'LAN': 'Langwiesen',
  'LAPR': 'Lancy-Pont-Rouge',
  'LAPU': 'La Punt Chamues-ch',
  'LARG': 'La Large-Journée',
  'LAT': 'Lattigen bei Spiez',
  'LATR': 'Lattrigen',
  'LAUT': 'Lauterbrunnen',
  'LAV': 'Lavorgo',
  'LAVI': 'Lavin',
  'LAWI': 'Langwies GR',
  'LAX': 'Lax',
  'LB': 'Lenzburg',
  'LBAD': 'Leissigbad (Agl)',
  'LBD': 'Root D4',
  'LBF': 'Liebefeld',
  'LCR': 'Le Creux',
  'LD': 'Le Landeron',
  'LDS': 'Landschlacht',
  'LE': 'Leuzigen',
  'LEBO': 'Les Bovets',
  'LECH': 'Léchelles',
  'LEI': 'Leibstadt',
  'LEIM': 'Leimbach AG',
  'LEN': 'Lengnau BE',
  'LENG': 'Lengwil',
  'LENI': 'Les Nicolets',
  'LENK': 'Lenk im Simmental',
  'LES': 'Lessoc',
  'LEY': 'Leysin-Feydey',
  'LEYG': 'Leysin-Grand-Hôtel',
  'LEYV': 'Leysin-Village',
  'LF': 'Läufelfingen',
  'LFG': 'Laufenburg',
  'LFN': 'Laufen',
  'LG': 'Lugano',
  'LGB': 'Leuggelbach',
  'LGFL': 'Lugano FLP',
  'LGP': 'Paradiso',
  'LGV': 'Lugano Vedeggio',
  'LH': 'Lanzenhäusern',
  'LHE': 'La Heutte',
  'LHO': 'Lindenholz',
  'LIES': 'Langwies ZH',
  'LIEU': 'Le Lieu',
  'LIN': 'Linthal',
  'LINB': 'Linthal Braunwaldbahn',
  'LIT': 'Luzern Littau',
  'LITT': 'Litti (Baar)',
  'LITZ': 'Litzirüti',
  'LK': 'Leuk',
  'LL': 'Lalden',
  'LLA': 'La Lance (diag)',
  'LN': 'Langnau i.E.',
  'LNG': 'Langnau-Gattikon',
  'LO': 'Locarno',
  'LOAN': 'Locarno S. Antonio',
  'LOC': 'Le Locle',
  'LOCF': 'Le Locle-Frontière',
  'LOEW': 'Muntelier-Löwenberg',
  'LOLU': 'Lohn-Lüterkofen',
  'LOM': 'Lommiswil',
  'LON': 'Lonay-Préverenges',
  'LONA': 'Lonay A (bif)',
  'LONB': 'Lonay B (bif)',
  'LOTZ': 'Lotzwil',
  'LP': 'La Plaine',
  'LPN': 'Laupen BE',
  'LQ': 'Landquart',
  'LQRI': 'Landquart Ried',
  'LS': 'Lausanne',
  'LSA': 'La Sarraz',
  'LSAL': 'Les Salines',
  'LSB': 'Liesberg',
  'LSCH': 'Lausanne-Chauderon',
  'LSFL': 'Lausanne-Flon',
  'LSG': 'Lichtensteig',
  'LSN': 'Lausen',
  'LSSB': 'Lausanne-Sébeillon',
  'LST': 'Liestal',
  'LSTN': 'Liestal Nord (Abzw)',
  'LT': 'Lausanne-Triage',
  'LTAB': 'Lausanne-Triage A/B',
  'LTD': 'Lausanne-Triage D',
  'LTE': 'Lausanne-Triage Est',
  'LTG': 'Langenthal GB',
  'LTH': 'Langenthal',
  'LTHG': 'Langenthal Gaswerk',
  'LTHS': 'Langenthal Süd',
  'LTIN': 'Langenthal Industrie Nord',
  'LTSA': 'Lausanne-Triage SALT',
  'LTY': 'Lutry',
  'LU': 'Luchsingen-Hätzingen',
  'LUC': 'Lucens',
  'LUCA': 'Lüen-Castiel',
  'LUE': 'Lüsslingen',
  'LUED': 'Lüdem',
  'LUEL': 'Lütschental',
  'LUES': 'Lüscherz',
  'LUET': 'Lütisburg',
  'LUGO': 'Lützelflüh-Goldbach',
  'LUMU': 'Lustmühle',
  'LUN': 'Lungern',
  'LUPF': 'Lupfig',
  'LUT': 'Luterbach-Attisholz',
  'LUY': 'Lussy FR',
  'LVE': 'Le Verney (embr)',
  'LY': 'Lyss',
  'LYGR': 'Lyss Grien',
  'LYS': 'Lyssach',
  'LZ': 'Luzern',
  'LZGB': 'Luzern Cargo',
  'LZSH': 'Luzern Steghof (Abzw)',
  'LZVH': 'Luzern Verkehrshaus',
  'MA': 'Martigny',
  'MABC': 'Martigny-Bourg CT',
  'MABO': 'Martigny-Bourg',
  'MACR': 'Martigny-Croix',
  'MADI': 'Madiswil',
  'MADU': 'Madulain',
  'MAE': 'Märwil',
  'MAEG': 'Mägenwil',
  'MAEN': 'Männedorf',
  'MAER': 'Märstetten',
  'MAG': 'Magadino-Vira',
  'MAGL': 'Magliaso',
  'MAGP': 'Magliaso Paese',
  'MAIF': 'Maiacher',
  'MAL': 'Malters',
  'MALA': 'Malans GR',
  'MALU': 'Martigny Aluminium (embr)',
  'MAM': 'Mammern',
  'MANE': 'Le Manège',
  'MANN': 'Mannenbach-Salenstein',
  'MAR': 'Maroggia-Melano',
  'MARA': 'Le Marais',
  'MARE': 'Les Marécottes',
  'MAS': 'Massongex',
  'MATA': 'Mattstetten (Abzw)',
  'MATE': 'Matten i.S.',
  'MATT': 'Hergiswil Matt',
  'MATZ': 'Matzingen',
  'MAU': 'Menznau',
  'MAUZ': 'Mauraz',
  'MAXP': 'Martigny-Expo',
  'MB': 'Malleray-Bévilard',
  'MBI': 'Matten b. Interlaken',
  'MD': 'Moudon',
  'MDE': 'Melide',
  'ME': 'Menziken',
  'MED': 'La Médettaz',
  'MEG': 'Meggen',
  'MEGZ': 'Meggen Zentrum',
  'MEL': 'Mellingen',
  'MELH': 'Mellingen Heitersberg',
  'MELN': 'Mellikon',
  'MELS': 'Mels',
  'MEN': 'Mendrisio',
  'MEP': 'Marin-Epagnier',
  'MERL': 'Merlischachen',
  'MEZ': 'Mezzovico',
  'MF': 'Maienfeld',
  'MG': 'Murg',
  'MGEN': 'Mörigen',
  'MGT': 'Murgenthal',
  'MH': 'Mühlehorn',
  'MHN': 'Mittelhäusern',
  'MI': 'Muri AG',
  'MIES': 'Mies',
  'MINU': 'Minusio',
  'MIRA': 'Miralago',
  'MIT': 'Mitlödi',
  'MKR': 'Meierskappel-Risch',
  'ML': 'Meilen',
  'MM': 'Müntschemier',
  'MMUH': 'Mittelmuhen',
  'MO': 'Mosen',
  'MOE': 'Möhlin',
  'MOEL': 'Mörel',
  'MOER': 'Mörschwil',
  'MOG': 'Mogelsberg',
  'MOOS': 'Moos',
  'MOR': 'Morges',
  'MORI': 'Montricher',
  'MOSE': 'Moosseedorf',
  'MOSM': 'Mendrisio S. Martino',
  'MOT': 'Môtiers NE',
  'MOTA': 'Morteratsch',
  'MOTU': 'Mumpé Tujetsch',
  'MOU': 'Moutier',
  'MPF': 'Mumpf',
  'MR': 'Meiringen',
  'MRAB': 'Meiringen Alpbach',
  'MRL': 'Moreillon',
  'MROS': 'Täsch Monte Rosa',
  'MRSS': 'Aareschlucht West',
  'MRT': 'Murten/Morat',
  'MS': 'Münsingen',
  'MSCH': 'Münsterlingen-Scherzingen',
  'MSPI': 'Münsterlingen Spital',
  'MST': 'Münchenstein',
  'MTB': 'Montbovon',
  'MTH': 'Monthey',
  'MTHH': 'Monthey-Hôpital',
  'MTHP': 'Monthey-En Place',
  'MTHV': 'Monthey-Ville',
  'MTL': 'Marthalen',
  'MTLN': 'Marthalen Nord',
  'MTM': 'Mettmenstetten',
  'MTR': 'Matran',
  'MU': 'Muttenz',
  'MUAU': 'Muriaux',
  'MUCO': 'Münchenwiler-Courgevaux',
  'MUE': 'Mülenen',
  'MUEB': 'Münchenbuchsee',
  'MUEH': 'Mühlau',
  'MUEL': 'Müllheim-Wigoltingen',
  'MUER': 'Mürren BLM',
  'MUET': 'Münster VS',
  'MUH': 'Muhen',
  'MUHN': 'Muhen Nord',
  'MUI': 'Le Muids',
  'MUND': 'Mundbach (Spw)',
  'MUO': 'Muolen',
  'MUSS': 'Mussachen',
  'MWIL': 'Münchwilen TG',
  'MX': 'Montreux',
  'NAEF': 'Näfels-Mollis',
  'NAEN': 'Nänikon-Greifensee',
  'NAET': 'Nätschen',
  'NB': 'Niederbipp',
  'NBD': 'Niederbipp Dorf',
  'NBT': 'Niederbottigen BN',
  'NE': 'Neuchâtel',
  'NEB': 'Nebikon',
  'NECB': 'Neuchâtel Champ-Bougin',
  'NEFD': 'Neuchâtel Cargo',
  'NEIR': 'Neirivue',
  'NELI': 'Neuchâtel Evole',
  'NEMA': 'Neuchâtel Est (bif)',
  'NEPS': 'Neuchâtel Port-de-Serrières',
  'NESE': 'Neuchâtel-Serrières',
  'NET': 'Netstal',
  'NEU': 'Neuthal',
  'NEUK': 'Neunkirch',
  'NEY': 'Neyruz FR',
  'NEYS': 'Les Neys',
  'NFCH': 'Neue Forch',
  'NG': 'Niederglatt ZH',
  'NGG': 'Neuenegg',
  'NGR': 'Neugrüt (Verzw)',
  'NH': 'Neuhausen',
  'NHB': 'Neuhausen Bad Bf',
  'NHBH': 'Neuhaus bei Hinteregg',
  'NHGR': 'Neuhausen Grenze DB',
  'NHOF': 'Neuenhof',
  'NHRH': 'Neuhausen Rheinfall',
  'NIBE': 'Nidau Beunden',
  'NID': 'Nidfurn-Haslen',
  'NIDA': 'Nidau',
  'NIE': 'Niederhasli',
  'NIIN': 'Niederbipp Industrie',
  'NK': 'Neukirch-Egnach',
  'NL': 'Nesslau-Neu St. Johann',
  'NM': 'Neumühle',
  'NO': 'Nottwil',
  'NOGG': 'St. Gallen Notkersegg',
  'NOI': 'Noiraigue',
  'NOMO': 'Le Noirmont',
  'NOU': 'Nieder- und Oberurnen',
  'NPLI': 'Neuchâtel Place Pury Littorail',
  'NR': 'Niederried',
  'NRRB': 'Niederrickenbach Station',
  'NS': 'Niederscherli',
  'NSRL': 'Neuchâtel Serrières Ruau',
  'NTEU': 'Niederteufen',
  'NV': 'La Neuveville',
  'NW': 'Niederweningen',
  'NWA': 'Niederwangen',
  'NWAL': 'Niederwald',
  'NWD': 'Niederweningen Dorf',
  'NY': 'Nyon',
  'OA': 'Oberaach',
  'OAB': 'Oberried am Brienzersee',
  'OB': 'Oberbuchsiten',
  'OBAL': 'Oberalppass',
  'OBB': 'Oberburg',
  'OBBI': 'Oberbipp',
  'OBEI': 'Oberei bei Wasen i.E.',
  'OBGE': 'Obergesteln',
  'OBK': 'Oberkirch LU',
  'OBW': 'Oberwald',
  'OBWAT': 'Oberwald Autoverlad',
  'OBZO': 'Oberzollikofen',
  'OD': 'Oberdiessbach',
  'ODF': 'Oberdorf SO',
  'OE': 'Oey-Diemtigen',
  'OEF': 'Oberentfelden',
  'OEFU': 'Oberentfelden Uerkenbrücke',
  'OEFW': 'Oberentfelden Engelplatz',
  'OEN': 'Oensingen',
  'OES': 'Oeschseite',
  'OF': 'Otelfingen',
  'OFI': 'Otelfingen Industrie',
  'OFR': 'Otelfingen Golfpark',
  'OGL': 'Oberglatt ZH',
  'OI': 'Oberrüti',
  'OIS': 'Oberwil im Simmental',
  'OKU': 'Oberkulm',
  'OL': 'Olten',
  'OLH': 'Olten Hammer',
  'OLLO': 'Ollon VD',
  'OLRB': 'Olten RB',
  'OLTU': 'Olten Tunnel (Spw)',
  'OMUH': 'Obermuhen',
  'ONB': 'Onnens-Bonvillars',
  'ONBP': 'Onnens-Bonvillars PMP',
  'OND': 'Ondallaz-L\'Alliaz',
  'OP': 'Opfikon',
  'OPP': 'Oppikon',
  'OPS': 'Opfikon Süd',
  'OR': 'Oron',
  'ORD': 'Oberrieden',
  'ORDD': 'Oberrieden Dorf',
  'ORIN': 'Orbe-Industrie (marchandises)',
  'ORS': 'Orsières',
  'ORT': 'Oberriet SG',
  'OS': 'Osogna-Cresciano',
  'OSBE': 'Ospizio Bernina',
  'OSS': 'Ossingen',
  'OST': 'Ostermundigen',
  'OTH': 'Othmarsingen',
  'OWA': 'Oberwangen',
  'OWT': 'Oberwinterthur',
  'PAL': 'Palézieux',
  'PALG': 'Palagnedra',
  'PALV': 'Palézieux-Village',
  'PALZ': 'Château-d\'Oex La Palaz',
  'PAPI': 'Papiermühle',
  'PAQ': 'Le Pâquier-Montbarry',
  'PASE': 'Pampigny-Sévery',
  'PASQ': 'Pasquerio (bin rac)',
  'PAY': 'Payerne',
  'PDM': 'Les Ponts-de-Martel',
  'PDS': 'Les Paluds',
  'PEI': 'Peist',
  'PEN': 'Pensier',
  'PF': 'Pfäffikon SZ',
  'PFAF': 'Pfaffensprung (Spw)',
  'PFL': 'Münchwilen Pflegeheim',
  'PFU': 'Pfungen',
  'PFZ': 'Pfäffikon ZH',
  'PIE': 'Pieterlen',
  'PIEO': 'Le Pied-d\'Or',
  'PLAC': 'Planchamp',
  'PLAM': 'Plambuit',
  'PLAN': 'Les Plantaz',
  'PLAS': 'Les Planches (Aigle)',
  'PLEI': 'Les Pléiades',
  'PLMO': 'Plan Morier',
  'POBR': 'Ponte Brolla',
  'POFA': 'Pont de Fayot',
  'POLD': 'Pollegio Sud (Dira)',
  'POLL': 'Pollegio',
  'POLN': 'Pollegio Nord (dira)',
  'POLS': 'Pollegio binario di sorpasso',
  'PON': 'Pontenet',
  'POR': 'Porrentruy',
  'PORE': 'Pontresina',
  'POS': 'Poschiavo',
  'POSS': 'Les Posses',
  'POTR': 'Ponte Tresa',
  'POZZ': 'Pozzo Negro (dira)',
  'PR': 'Pratteln',
  'PRAL': 'Les Pralies',
  'PRCH': 'Prilly-Chasseur',
  'PRED': 'Preda',
  'PREP': 'Pré-Petitjean',
  'PRES': 'Le Prese',
  'PRL': 'Prélionne',
  'PRLZ': 'Prélaz-sur-Blonay',
  'PRMA': 'Prilly-Malley',
  'PRSR': 'Pratteln Salina Raurica',
  'PRST': 'La Presta Mines d\'asphalte',
  'PRUW': 'Pratteln Ueberwerfung',
  'PT': 'Le Pont',
  'PTC': 'Pont-Céard',
  'PTD': 'Pont-de-Drapel',
  'PTM': 'Punt Muragl',
  'PTMA': 'Petit-Martel',
  'PTME': 'Petit-Martel-Est',
  'PTMS': 'Punt Muragl Staz',
  'PTR': 'Pont du Rhône',
  'PU': 'Pully',
  'PUI': 'Puidoux',
  'PUN': 'Pully-Nord',
  'QUA': 'Quartino',
  'RA': 'Ramsen',
  'RAET': 'Räterschen',
  'RAM': 'Ramsei',
  'RAND': 'Randa',
  'RAR': 'Raron',
  'RARK': 'Rarnerkumme (Spw)',
  'RASU': 'Rabius-Surrein',
  'RBA': 'Rohrbach',
  'RBG': 'Rothenburg Station',
  'RBGD': 'Emmenbrücke Kapf',
  'RBL': 'Zürich RB Limmattal',
  'RBLA': 'RBL A-Gruppe',
  'RBLP': 'Zürich RB Limmattal Depot/Bau',
  'RCH': 'Bern Riedbach',
  'RCHG': 'Roches Grises',
  'RCK': 'Rheineck',
  'RCY': 'Le Rocheray',
  'RDM': 'Riedmatt SZ',
  'RE': 'Renan BE',
  'REAL': 'Realp',
  'REALAT': 'Realp Autoverlad',
  'REAZ': 'Rennaz (Leysin)',
  'REB': 'Rebstein-Marbach',
  'REC': 'Reconvilier',
  'RECK': 'Reckingen VS',
  'REG': 'Regensdorf-Watt',
  'REI': 'Reinach AG',
  'REID': 'Reiden',
  'REIF': 'Reichenau Farsch (Abzw)',
  'REIK': 'Reichenbach im Kandertal',
  'REIN': 'Reinach AG Nord',
  'REIT': 'Reichenau-Tamins',
  'REK': 'Rekingen AG',
  'RELP': 'Renens VD Larges Pièces (embr)',
  'REMA': 'Remaufens',
  'REMI': 'Reinach AG Mitte',
  'REN': 'Renens VD',
  'RENB': 'Renens VD Est (bif)',
  'RENE': 'Renens VD Entrepôts',
  'RENO': 'Renens VD Ouest (bif)',
  'REPP': 'Reppischhof',
  'REU': 'Reuchenette-Péry',
  'REUS': 'Les Reussilles',
  'REUT': 'Reutlingen',
  'REV': 'Reverolle',
  'REYM': 'Le Reymond',
  'RF': 'Rheinfelden',
  'RFAU': 'Rheinfelden Augarten',
  'RG': 'Reichenburg',
  'RGD': 'Ringoldingen',
  'RH': 'Romanshorn',
  'RHAE': 'Rhäzüns',
  'RHGB': 'Romanshorn GB',
  'RI': 'Richterswil',
  'RIAZ': 'Riazzino',
  'RIB': 'Rivera-Bironico',
  'RID': 'Riddes',
  'RIEB': 'Riehen',
  'RIET': 'Rietheim',
  'RIHO': 'Riedholz',
  'RIK': 'Rickenbach-Attikon',
  'RILI': 'Ringlikon',
  'RIN': 'Ringgenberg',
  'RINZ': 'Riehen Niederholz',
  'RIPE': 'Les Ripes',
  'RITH': 'St. Gallen Riethüsli',
  'RITI': 'Rietli',
  'RIV': 'Rivaz',
  'RK': 'Rotkreuz',
  'RLG': 'Rümlingen',
  'RMZ': 'Rämismühle-Zell',
  'RN': 'Rikon',
  'RO': 'Rodi-Fiesso',
  'ROBG': 'Roggwil-Berg',
  'ROBU': 'Roggwil Buchägerten',
  'ROC': 'Roche VD',
  'ROG': 'Roggwil-Wynau',
  'ROGD': 'Roggwil Dorf',
  'ROL': 'Rolle',
  'ROM': 'Romont FR',
  'RORE': 'Rodels-Realta',
  'ROS': 'Rosé',
  'ROSC': 'Roggwil Schmitten',
  'ROSI': 'Rossinière',
  'ROSL': 'Romanel-sur-Lausanne',
  'ROSS': 'Rosshäusern',
  'ROTH': 'Rothenbrunnen',
  'ROU': 'Rougemont',
  'ROUL': 'La Roulaz',
  'RS': 'Rorschach',
  'RSGB': 'Rorschach GB',
  'RSHF': 'Rorschach Hafen',
  'RSST': 'Rorschach Stadt',
  'RT': 'Riet (Verzw)',
  'RTAL': 'Rosental',
  'RTEM': 'Route de Morgins',
  'RTH': 'Rüthi SG',
  'RTI': 'Rüti bei Büren',
  'RTR': 'Rothrist',
  'RTRH': 'Rothrist GB',
  'RTT': 'Rothenthurm',
  'RTW': 'Riedtwil',
  'RU': 'Rupperswil',
  'RUAZ': 'La Ruaz',
  'RUB': 'Rubigen',
  'RUD': 'Rudolfstetten',
  'RUDB': 'Ruderbach',
  'RUE': 'Rüti ZH',
  'RUEM': 'Rümlang',
  'RUEN': 'Rümikon AG',
  'RUER': 'Rueras',
  'RUES': 'Rüschlikon',
  'RUET': 'Rüti GL',
  'RUEU': 'Rueun',
  'RUHO': 'Rudolfstetten Hofacker',
  'RUS': 'Russin',
  'RW': 'Rapperswil SG',
  'RYAB': 'Rynächt (Abzw)',
  'RYN': 'Rynächt Nord',
  'RYUE': 'Rynächt Ueberholgleisanlage',
  'RZ': 'Rafz',
  'RZO': 'Ranzo-S. Abbondio',
  'SA': 'Sargans',
  'SAAC': 'Sandacher (Spw)',
  'SAAN': 'Saanen',
  'SAAS': 'Saas im Prättigau',
  'SAAV': 'Sagliains Autoverlad',
  'SACH': 'Sachseln',
  'SAEG': 'La Sagne-Eglise',
  'SAF': 'Safenwil',
  'SAGL': 'Sagliains',
  'SAGN': 'La Sagne',
  'SAIG': 'Saignelégier',
  'SAL': 'Salgesch',
  'SALE': 'Sâles',
  'SAM': 'Samstagern',
  'SAME': 'Samedan',
  'SAMO': 'Saanenmöser',
  'SAN': 'S. Antonino',
  'SAPL': 'Sammelplatz',
  'SAR': 'Sarnen',
  'SAS': 'Salez-Sennwald',
  'SASL': 'Sargans Schleife (Verzw)',
  'SAT': 'Sattel-Aegeri',
  'SATT': 'Sattel',
  'SAX': 'Saxon',
  'SB': 'Sandbüchel',
  'SBA': 'Steigbach',
  'SBAD': 'Schinznach Bad',
  'SBAR': 'Schwarzer Bären',
  'SBG': 'Sihlbrugg',
  'SBL': 'St-Blaise CFF',
  'SBLB': 'St-Blaise-Lac',
  'SBN': 'Subingen',
  'SBR': 'Schwarzwasserbrücke',
  'SCAE': 'Schänis',
  'SCAN': 'S-chanf',
  'SCB': 'Sonceboz-Sombeval',
  'SCBG': 'Schwarzenburg',
  'SCBS': 'Schönbühl RBS',
  'SCBU': 'Schübelbach-Buttikon',
  'SCDE': 'Schwende',
  'SCEA': 'Schachen (Gais)',
  'SCGR': 'Schmitten GR Landwasserviadukt',
  'SCH': 'Schachen (Herisau)',
  'SCHA': 'Schachen LU',
  'SCHB': 'Schönbühl SBB',
  'SCHD': 'Schwanden GL',
  'SCHF': 'Schöftland',
  'SCHH': 'Schüpfheim',
  'SCHI': 'Schindellegi-Feusisberg',
  'SCHK': 'Schottikon',
  'SCHL': 'Schlieren',
  'SCHN': 'Schlattingen',
  'SCHO': 'Schöfflisdorf-Oberweningen',
  'SCHT': 'Schlatt TG',
  'SCHW': 'Schwyz',
  'SCHZ': 'Schwarzenbach SG',
  'SCI': 'Les Sciernes',
  'SCLC': 'St-Cergue Les Cheseaux',
  'SCME': 'Schmerikon',
  'SCMI': 'Schmitten FR',
  'SCN': 'Schalunen',
  'SCNW': 'Schöftland Nordweg',
  'SCOE': 'Schönenwerd SO',
  'SCOO': 'Schönenwerd SO Ost (Spw)',
  'SCR': 'Schönried',
  'SCRN': 'Scheuren',
  'SCRS': 'Schiers',
  'SCSH': 'Schönbühl Shoppyland',
  'SCTA': 'Scuol-Tarasp',
  'SCUE': 'Schüpfen',
  'SCWE': 'Schwerzenbach ZH',
  'SD': 'Saland',
  'SDO': 'Schinznach Dorf',
  'SDY': 'Sendy-Sollard',
  'SE': 'Seon',
  'SEC': 'Le Séchey',
  'SED': 'Sedrun',
  'SEEB': 'Seebleiche',
  'SEEV': 'Seewis-Pardisla',
  'SEG': 'Segnas',
  'SEL': 'Selzach',
  'SELF': 'Klosters Selfranga',
  'SEM': 'Sempach-Neuenkirch',
  'SEMB': 'Sembrancher',
  'SEMS': 'Semsales',
  'SEN': 'Le Sentier-L\'Orient',
  'SENO': 'Seon Nord',
  'SEP': 'Le Sépey',
  'SERN': 'Serneus',
  'SERO': 'Serocca',
  'SETB': 'Sumiswald-Grünen ETB',
  'SEU': 'Seuzach',
  'SEV': 'Sevelen',
  'SEVA': 'Sévaz (embr)',
  'SF': 'Seftigen',
  'SFM': 'S-chanf Marathon',
  'SG': 'St. Gallen',
  'SGAR': 'Schützengarten',
  'SGBI': 'St. Gallen Birnbäumen',
  'SGBR': 'St. Gallen Bruggen',
  'SGF': 'St. Gallen St. Fiden',
  'SGGB': 'St. Gallen GB',
  'SGHA': 'St. Gallen Haggen',
  'SGMP': 'St. Gallen Marktplatz',
  'SGO': 'Le Solliat-La Golisse',
  'SGWI': 'St. Gallen Winkeln',
  'SH': 'Schaffhausen',
  'SHAL': 'Schweizerhalle',
  'SHAU': 'Siegershausen',
  'SHF': 'Zürich Schweighof',
  'SHIE': 'Schafhausen i.E.',
  'SHNO': 'Schaffhausen Nord',
  'SHRB': 'Schaffhausen GB',
  'SHS': 'St. Gallen Schülerhaus',
  'SHSU': 'Schaffhausen Süd',
  'SIA': 'Sihlau',
  'SIB': 'Siebnen-Wangen',
  'SIE': 'Sierre/Siders',
  'SIFI': 'Siselen-Finsterhennen',
  'SIG': 'Siggenthal-Würenlingen',
  'SIGI': 'Sigirino',
  'SIGN': 'Signau',
  'SILB': 'Silberen (Abzw)',
  'SILS': 'Sils im Domleschg (Abzw)',
  'SINS': 'Sins',
  'SIO': 'Sion',
  'SIPO': 'Siporex (embr)',
  'SIR': 'Sirnach',
  'SIS': 'Sissach',
  'SIT': 'Sitterdorf',
  'SIW': 'Sihlwald',
  'SIXF': 'Six-Fontaines',
  'SK': 'Sisikon',
  'SKY': 'Sennhof-Kyburg',
  'SL': 'St-Léonard',
  'SLB': 'Sur-le-Buis',
  'SLF': 'Schloss Laufen am Rheinfall',
  'SLG': 'Sulgen',
  'SLN': 'Sisseln',
  'SLV': 'Salvan',
  'SM': 'St-Maurice',
  'SMAR': 'Solduno S. Martino',
  'SMG': 'St. Margrethen SG',
  'SMOR': 'St. Moritz',
  'SN': 'S. Nazzaro',
  'SNAG': 'Scharnageln',
  'SNK': 'St. Niklaus VS',
  'SO': 'Solothurn',
  'SOAD': 'Solothurn Allmend',
  'SOBT': 'Solothurn Baseltor',
  'SOGO': 'Sorengo',
  'SOLD': 'Solduno',
  'SOM': 'Sommerau',
  'SONZ': 'Sonzier',
  'SOOD': 'Sood-Oberleimbach',
  'SOR': 'Sorvilier',
  'SORL': 'Sorengo Laghetto',
  'SOST': 'Solothurn Sternen',
  'SOY': 'Soyhières',
  'SP': 'Spiez',
  'SPAB': 'Spiez (Abzw)',
  'SPAO': 'Bellinzona S. Paolo',
  'SPEI': 'Speicher',
  'SPIN': 'Spinas',
  'SPIS': 'St. Gallen Spisertor',
  'SPIT': 'Spital Zollikerberg',
  'SPMS': 'Spiezmoos Süd',
  'SRND': 'Sarnen Nord',
  'SROC': 'Sur Roche',
  'SS': 'Sursee',
  'SSMF': 'Sedrun SMF',
  'SSP': 'St-Sulpice NE',
  'SST': 'Schnaus-Strada',
  'SSTA': 'Stansstad',
  'SSWM': 'Sursee Wassermatte',
  'ST': 'St-Triphon',
  'STA': 'Staad SG',
  'STAE': 'Stäfa',
  'STAF': 'Stabio',
  'STAL': 'Stalden i.E.',
  'STAN': 'Stans',
  'STAO': 'Stabio Cargo',
  'STAS': 'Stalden-Saas',
  'STB': 'Steinebrunn',
  'STBA': 'Steinibach',
  'STBG': 'Steinerberg',
  'STCE': 'St-Cergue',
  'STCH': 'Steinach',
  'STCR': 'Ste-Croix',
  'STD': 'Le Stand',
  'STE': 'Steinhausen',
  'STEE': 'Steinegg',
  'STEF': 'Steffisburg',
  'STEL': 'St-Eloi',
  'STER': 'St. Erhard-Knutwil',
  'STET': 'Stettbach',
  'STFE': 'Teufen AR Stofel',
  'STG': 'Steg',
  'STGE': 'St. German (Abzw)',
  'STGI': 'St-Gingolph (Suisse)',
  'STGR': 'St-Triphon-Gare',
  'STI': 'St-Imier',
  'STJ': 'Morges-St-Jean',
  'STK': 'Steckborn',
  'STKA': 'St. Katharinen',
  'STKT': 'St. Katharinental',
  'STLE': 'St-Légier-Gare',
  'STLS': 'St-Triphon Lessus',
  'STLV': 'St-Légier-Village',
  'STM': 'Stammheim',
  'STMR': 'Steinmaur',
  'STN': 'Steinen',
  'STOI': 'Stöckli',
  'STOS': 'Stoss AR',
  'STP': 'St-Prex',
  'STPM': 'St. Peter-Molinis',
  'STR': 'Stein am Rhein',
  'STRH': 'Strahlholz',
  'STRI': 'Steinhausen Rigiblick',
  'STS': 'Stein-Säckingen',
  'STSA': 'St-Saphorin',
  'STST': 'St. Stephan',
  'STTF': 'Sternen bei Teufen',
  'STTL': 'Stettlen',
  'STU': 'Studen BE',
  'STUA': 'Studen Auto',
  'STVI': 'St-Triphon-Village',
  'SU': 'St-Ursanne',
  'SUB': 'Suberg-Grossaffoltern',
  'SUCH': 'Genolier Sus-Châtel',
  'SUCU': 'Sumvitg-Cumpadials',
  'SUGI': 'Sugiez',
  'SUGN': 'Sugnens',
  'SUHM': 'Suhr Migros',
  'SUHR': 'Suhr',
  'SURA': 'Surava',
  'SURB': 'St. Urban',
  'SURO': 'Surovas',
  'SUS': 'Susch',
  'SUTZ': 'Sutz',
  'SV': 'Sonvilier',
  'SW': 'Solothurn West',
  'SWB': 'Schwäbis',
  'SWD': 'Schwendi bei Heiden',
  'SWDG': 'Schwendi bei Grindelwald',
  'SWG': 'Sumiswald-Grünen',
  'SY': 'Satigny',
  'TA': 'Tavannes',
  'TABR': 'Tavanasa-Breil/Brigels',
  'TAEG': 'Tägerwilen-Gottlieben',
  'TAEM': 'Tägerwilen Dorf',
  'TAEN': 'Tägerschen',
  'TAES': 'Täsch',
  'TAEU': 'Täuffelen',
  'TAN': 'Tannay',
  'TAV': 'Taverne-Torricella',
  'TD': 'Tann-Dürnten',
  'TDT': 'La Tour-de-Trême Ronclina',
  'TEGN': 'Tegna',
  'TEN': 'Tenero',
  'TER': 'Territet',
  'TEU': 'Teufenthal AG',
  'TEUF': 'Teufen AR',
  'TG': 'Turgi',
  'TH': 'Thun',
  'THA': 'Thayngen',
  'THB': 'Thun GB',
  'THBU': 'Thalbrücke',
  'THO': 'Thörishaus Station',
  'THOD': 'Thörishaus Dorf',
  'THS': 'Thusis',
  'THU': 'Thurnen',
  'TI': 'Tägertschi',
  'TICA': 'Tiefencastel',
  'TINE': 'La Tine',
  'TK': 'Tecknau',
  'TKLL': 'Léchelles Tanklager (embr)',
  'TLH': 'Thalheim-Altikon',
  'TO': 'Toffen',
  'TOA': 'Tobel-Affeltrangen',
  'TOUR': 'La Tour-de-Peilz',
  'TOUV': 'La Tour-de-Trême',
  'TR': 'Travers',
  'TRAM': 'Tramelan',
  'TRCH': 'Tramelan-Chalet',
  'TRDE': 'Tramelan-Dessous',
  'TRED': 'Trélex dépôt',
  'TREL': 'Trélex',
  'TRET': 'Le Trétien',
  'TRHA': 'Trasadingen',
  'TRI': 'Trimbach',
  'TRIB': 'Triboltingen',
  'TRIN': 'Trin',
  'TRIS': 'Trimmis',
  'TRLI': 'Zürich Triemli',
  'TRO': 'Trogen',
  'TROI': 'Troistorrents',
  'TRUB': 'Trübbach',
  'TRUN': 'Trun',
  'TRW': 'Triengen-Winikon',
  'TSCH': 'Trubschachen',
  'TSSE': 'Tschamut-Selva',
  'TU': 'Turbenthal',
  'TUE': 'Tüscherz',
  'TUI': 'Les Tuileries',
  'TUIE': 'Tuilerie',
  'TUR': 'Turtmann',
  'TUS': 'Tusinge',
  'TW': 'Thalwil',
  'TWN': 'Twann',
  'UE': 'Uetendorf',
  'UEA': 'Uetendorf Allmend',
  'UEBE': 'Uetliberg',
  'UER': 'Uerikon',
  'UET': 'Uetikon',
  'UIWA': 'Uitikon Waldegg',
  'UKU': 'Unterkulm',
  'UKUN': 'Unterkulm Nord',
  'ULR': 'Ulrichen',
  'UNOB': 'Unterentfelden Oberdorf',
  'UNPO': 'Unterentfelden Post',
  'UNT': 'Unterterzen',
  'UNZO': 'Unterzollikofen',
  'UPRI': 'Union-Prilly',
  'UR': 'Urnäsch',
  'URD': 'Urdorf',
  'URDW': 'Urdorf Weihermatt',
  'URTN': 'Urtenen',
  'UST': 'Uster',
  'UT': 'Utzenstorf',
  'UTI': 'Uttigen',
  'UTW': 'Uttwil',
  'UVAZ': 'Untervaz-Trimmis',
  'UZ': 'Uznach',
  'UZW': 'Uzwil',
  'VAL': 'Vallorbe',
  'VALF': 'Vallorbe-Frontière',
  'VALI': 'Val-d\'Illiez',
  'VASA': 'Valendas-Sagogn',
  'VASM': 'Valeyres-sous-Montagny',
  'VAU': 'Vaumarcus',
  'VAUL': 'Vaulruz-Nord',
  'VAUS': 'Vaulruz-Sud',
  'VD': 'Vauderens',
  'VECA': 'Vernand-Camarès',
  'VECH': 'Vechigen',
  'VEGL': 'Vers-l\'Eglise',
  'VEMC': 'Vernayaz MC',
  'VEMO': 'Versmont',
  'VEND': 'Vendlincourt',
  'VER': 'Les Verrières',
  'VERC': 'Verschiez',
  'VERD': 'Verdasio',
  'VERF': 'Les Verrières-Frontière',
  'VERI': 'La Verrerie',
  'VERN': 'Vernayaz',
  'VESA': 'Versam-Safien',
  'VESC': 'Verscio',
  'VEY': 'Veytaux-Chillon',
  'VG': 'Villars-sur-Glâne',
  'VI': 'Visp',
  'VIAB': 'Villars-Bozon',
  'VIAR': 'Villars-sur-Ollon',
  'VIGO': 'Villars-sur-Ollon Golf',
  'VIL': 'Villeneuve VD',
  'VIO': 'Vionnaz',
  'VM': 'Meyrin',
  'VMC': 'Vernier-Meyrin Cargo',
  'VOEG': 'Vögelinsegg',
  'VOU': 'Vouvry',
  'VSX': 'Versoix',
  'VT': 'Villeret',
  'VTE': 'Villette VD',
  'VU': 'Vufflens-la-Ville',
  'VUA': 'Vuadens-Sud',
  'VUAP': 'La Vuarpillière',
  'VUAR': 'Vuarennes',
  'VUF': 'Vufflens-le-Château',
  'VUIB': 'Vuiteboeuf',
  'VV': 'Vevey',
  'VVFU': 'Vevey-Funi',
  'VVVI': 'Vevey Vignerons',
  'VY': 'Villy',
  'VZ': 'Villaz-St-Pierre',
  'W': 'Winterthur',
  'WA': 'Wattwil',
  'WAA': 'Wangen an der Aare',
  'WAB': 'Waldibrücke',
  'WAE': 'Wädenswil',
  'WAEN': 'Wängi',
  'WAIE': 'Wasen i.E.',
  'WAL': 'Walenstadt',
  'WALG': 'Waldburg',
  'WALK': 'Walkringen',
  'WALS': 'Waltenschwil',
  'WALZ': 'Walzenhausen',
  'WARS': 'Wartensee',
  'WAS': 'Wassen',
  'WASS': 'Wasserauen',
  'WAST': 'Walterswil-Striegel',
  'WAU': 'Wauwil',
  'WAVU': 'Waltensburg/Vuorz',
  'WB': 'Worb SBB',
  'WBA': 'Weissenbach',
  'WBB': 'Wabern bei Bern',
  'WBG': 'Warmesberg',
  'WBL': 'Worblaufen',
  'WBOL': 'Wangen bei Olten',
  'WCH': 'Wichtrach',
  'WCHO': 'Walchwil Hörndli',
  'WCHW': 'Walchwil',
  'WD': 'Wiesendangen',
  'WE': 'Wettingen',
  'WEBM': 'Weberei Matzingen',
  'WEGG': 'Winteregg',
  'WEIS': 'Weissbad',
  'WEN': 'Wengi',
  'WF': 'Weinfelden',
  'WFKV': 'Weinfelden KVA Thurgau (Abzw)',
  'WFS': 'Weinfelden Süd',
  'WG': 'Weissenburg',
  'WGR': 'Winterthur Grüze',
  'WH': 'Wolhusen',
  'WHE': 'Winterthur Hegi',
  'WHW': 'Wolhusen Weid',
  'WI': 'Wildegg',
  'WIED': 'Wiedlisbach',
  'WIES': 'Davos Wiesen',
  'WIG': 'Wiggen',
  'WIGR': 'Wiesengrund',
  'WIHA': 'Wilchingen-Hallau',
  'WIL': 'Wil SG',
  'WILA': 'Wila',
  'WILD': 'Wilderswil',
  'WILE': 'Herisau Wilen',
  'WILN': 'Wilen bei Wollerau',
  'WILO': 'Wil Ost',
  'WIN': 'Winkel am Zürichsee',
  'WIT': 'Wittenbach',
  'WITO': 'Wienacht-Tobel',
  'WK': 'Weiach-Kaiserstuhl',
  'WKD': 'Wankdorf (Abzw)',
  'WL': 'Wald ZH',
  'WLTK': 'Waltikon',
  'WM': 'Wimmis',
  'WN': 'Weesen',
  'WO': 'Wohlen AG',
  'WOBO': 'Worbboden',
  'WOFU': 'Wohlen Fulenbach',
  'WOL': 'Wollerau',
  'WOOB': 'Wohlen Oberdorf',
  'WOS': 'Wolfenschiessen',
  'WP': 'Wildpark-Höfli',
  'WR': 'Wiler',
  'WS': 'Wallisellen',
  'WSAU': 'Willisau',
  'WSEE': 'Winterthur Seen',
  'WST': 'Werthenstein',
  'WSTA': 'Waldstatt',
  'WTOE': 'Winterthur Töss',
  'WUE': 'Wünnewil',
  'WUER': 'Würenlos',
  'WWAL': 'Winterthur Wallrüti',
  'WWE': 'Winterthur West (Abzw)',
  'WWUE': 'Winterthur Wülflingen',
  'WY': 'Wynigen',
  'WZ': 'Wetzikon ZH',
  'YENS': 'Yens',
  'YND': 'Yvonand',
  'YV': 'Yverdon-les-Bains',
  'YVWB': 'Yverdon William Barbey',
  'ZAE': 'Zäziwil',
  'ZAF': 'Zürich Affoltern',
  'ZALT': 'Zizers Altlöser',
  'ZAS': 'Zürich Altstetten',
  'ZB': 'Ziegelbrücke',
  'ZBR': 'Zihlbrücke',
  'ZBRU': 'Zürich Brunau',
  'ZBZ': 'Zürich Binz',
  'ZELL': 'Zell LU',
  'ZEN': 'Zürich Enge',
  'ZERM': 'Zermatt',
  'ZETZ': 'Zetzwil',
  'ZEZ': 'Zernez',
  'ZF': 'Zofingen',
  'ZFFR': 'Frauenfeld Zuckerrüben',
  'ZFH': 'Zürich Flughafen',
  'ZG': 'Zug',
  'ZGCA': 'Zug Casino',
  'ZGFR': 'Zug Fridbach',
  'ZGH': 'Zürich Giesshübel',
  'ZGO': 'Zug Oberwil',
  'ZGPP': 'Zug Postplatz',
  'ZGSE': 'Zug Schutzengel',
  'ZGUB': 'Zürich Gubrist',
  'ZHDB': 'Zürich Hardbrücke',
  'ZHER': 'Zürich Herdern Abstellgruppe',
  'ZIE': 'St. Urban Ziegelei',
  'ZIM': 'Zimeysa',
  'ZIZ': 'Zizers',
  'ZIZS': 'Zizers SBB',
  'ZK': 'Zollikon',
  'ZKBG': 'Zollikerberg',
  'ZLE': 'Zürich Leimbach',
  'ZMA': 'Zürich Manegg',
  'ZMUE': 'Zürich Mülligen',
  'ZO': 'Zollbrück',
  'ZOER': 'Zürich Oerlikon',
  'ZOL': 'Zollikofen',
  'ZOLW': 'Zollikofen West (Spw)',
  'ZOO': 'Crémines-Zoo',
  'ZSAA': 'Zürich Saalsporthalle',
  'ZSEB': 'Zürich Seebach',
  'ZSEL': 'Zürich Selnau',
  'ZSTH': 'Zürich Stadelhofen',
  'ZTB': 'Zürich Tiefenbrunnen',
  'ZUE': 'Zürich HB',
  'ZUEM': 'Zürchersmühle',
  'ZUER': 'Zürich Rehalp',
  'ZUFH': 'Zufikon Hammergut',
  'ZUFI': 'Zufikon',
  'ZUM': 'Zumikon',
  'ZUOZ': 'Zuoz',
  'ZUSZ': 'Zürich HB SZU',
  'ZVB': 'Zürich Vorbahnhof',
  'ZVBS': 'Zürich Vorbahnhof Süd',
  'ZVBW': 'Zürich Vorbahnhof West',
  'ZW': 'Zweisimmen',
  'ZWBR': 'Zweibrücken',
  'ZWD': 'Zweidlen',
  'ZWEI': 'Zweilütschinen',
  'ZWG': 'Zwingen',
  'ZWIE': 'Zürich Wiedikon',
  'ZWIP': 'Zürich Wipkingen',
  'ZWOL': 'Zürich Wollishofen',
  'ZZ': 'Bad Zurzach',
};
