// Swiss railway stations and traffic points
// Source: https://data.sbb.ch/explore/dataset/dienststellen-gemass-opentransportdataswiss/
// Filter: TRAIN stops + traffic points with letter-only codes
// Query: /api/explore/v2.1/catalog/datasets/dienststellen-gemass-opentransportdataswiss/exports/json
//   ?select=abbreviation,designationofficial
//   &where=(meansoftransport="TRAIN" OR (meansoftransport IS NULL AND trafficpoint="true"))
//     AND abbreviation IS NOT NULL AND isocountrycode="CH"
//   &limit=-1

// Stations: [name, isTrainStop]
export const STATIONEN: Record<string, [string, boolean]> = {
  'AA': ['Aarau', true],
  'AAGB': ['Aarau GB', false],
  'AARS': ['Aarwangen Schloss', true],
  'AARV': ['Aarwangen Vorstadt', true],
  'AARW': ['Aarwangen', true],
  'AAT': ['Aathal', true],
  'AB': ['Ausserberg', true],
  'ABE': ['Aarberg', true],
  'ABO': ['Aarburg-Oftringen', true],
  'ACLA': ['Acla da Fontauna', true],
  'AD': ['Aadorf', true],
  'ADF': ['Alpnach Dorf', true],
  'ADL': ['Adelrain (Abzw)', false],
  'ADW': ['Adliswil', true],
  'ADZ': ['Ardez', true],
  'AE': ['Aesch BL', true],
  'AEF': ['Aefligen', true],
  'AF': ['Affoltern am Albis', true],
  'AFWE': ['Affoltern-Weier', true],
  'AGHO': ['Aigle-Parc Aventure', true],
  'AGIP': ['Monthey Agip (embr)', false],
  'AGNO': ['Agno', true],
  'AHAU': ['Altishausen', false],
  'AI': ['Airolo', true],
  'AIG': ['Aigle', true],
  'AIGD': ['Aigle-Dépôt', true],
  'AIGM': ['Aigle-Place-du-Marché', true],
  'AIGT': ['Aigle-Château', true],
  'AL': ['Altdorf UR', true],
  'ALBE': ['Albeuve', true],
  'ALD': ['Luzern Allmend/Messe', true],
  'ALGR': ['Alp Grüm', true],
  'ALIL': ['Areuse Les Isles Littorail', true],
  'ALIT': ['Areuse Littorail', true],
  'ALL': ['Allaman', true],
  'ALLC': ['Alle Cargo Centre-Ajoie', false],
  'ALLE': ['Alle', true],
  'ALLI': ['Allières', true],
  'ALN': ['Altnau', true],
  'ALPS': ['Gonten Alpsteinblick', true],
  'ALRH': ['Altenrhein', false],
  'ALST': ['Altstätten Stadt', true],
  'ALT': ['Altstätten SG', true],
  'ALTD': ['Altendorf', true],
  'ALV': ['Alvaneu', true],
  'AN': ['Andelfingen', true],
  'AND': ['Andermatt', true],
  'AP': ['Ambrì-Piotta', true],
  'APPL': ['Apples', true],
  'APPZ': ['Appenzell', true],
  'ARB': ['Arbon', true],
  'ARBS': ['Arbon Seemoosriet', true],
  'ARCA': ['Archy A (bif)', false],
  'ARCH': ['Arch', false],
  'ARCY': ['Archy (bif)', false],
  'ARD': ['Ardon', true],
  'ARN': ['Arnegg', true],
  'ARNO': ['Les Arnoux', true],
  'AROS': ['Arosa', true],
  'ARVE': ['Arveyes', true],
  'ARZ': ['Arzier', true],
  'AS': ['Amsteg-Silenen', false],
  'ASGR': ['Amsteg Grund (Agl)', false],
  'ASNS': ['Assens', true],
  'ASSE': ['L\'Asse', true],
  'AST': ['Alpnachstad', true],
  'AT': ['Altmatt', true],
  'ATOR': ['Aarau Torfeld', true],
  'ATOS': ['Aareschlucht Ost (Bahn)', true],
  'ATTI': ['Attiswil', true],
  'AU': ['Au ZH', true],
  'AUSG': ['Au SG', true],
  'AUV': ['Auvernier', true],
  'AV': ['Avenches', true],
  'AVA': ['Les Avants', true],
  'AVIO': ['Les Aviolats', true],
  'AVLI': ['Auvernier Littorail', true],
  'AVRY': ['Avry-Matran', true],
  'AW': ['Amriswil', true],
  'AX': ['Arnex', true],
  'AZO': ['Alter Zoll', true],
  'BAA': ['Baar', true],
  'BAAL': ['Baar Lindenpark', true],
  'BAAN': ['Baar Neufeld', true],
  'BAD': ['Basel Bad Bf', true],
  'BADH': ['Basel Bad Rbf KH (Abzw)', false],
  'BAE': ['Bäch SZ', true],
  'BAER': ['Bärschwil', false],
  'BAET': ['Bäretswil Tobel (Agl)', false],
  'BAEW': ['Bäretswil', true],
  'BAL': ['Balerna', true],
  'BALL': ['Ballens', true],
  'BAN': ['Bannwil', true],
  'BARB': ['Gryon Barboleuse', true],
  'BASM': ['Balerna per Smistamento (bif)', false],
  'BASS': ['Bassins', true],
  'BAU': ['Baulmes', true],
  'BAV': ['Bavois', true],
  'BAZ': ['Bazenheid', true],
  'BAZZ': ['Bazenheid ZAB (Agl)', false],
  'BBK': ['Büron-Bad Knutwil', false],
  'BCHX': ['Bois-de-Chexbres', true],
  'BCT': ['Boncourt', true],
  'BD': ['Baden', true],
  'BDF': ['Burgdorf', true],
  'BDFB': ['Burgdorf Buchmatt', true],
  'BDFS': ['Burgdorf Steinhof', true],
  'BDO': ['Baden Oberstadt', false],
  'BDR': ['Boudry', true],
  'BDWE': ['Bei den Weihern', true],
  'BEAI': ['Bel-Air LEB', true],
  'BEBR': ['Bergün/Bravuogn', true],
  'BEDI': ['Bernina Diavolezza', true],
  'BEFR': ['Bergfrieden', true],
  'BEL': ['Bellinzona', true],
  'BELA': ['Bernina Lagalb', true],
  'BELE': ['Bellach Industrie', false],
  'BELL': ['Bellach', true],
  'BELV': ['Bellevue NE', false],
  'BEM': ['Le Bémont JU', true],
  'BEMG': ['Bettmeralp Talstation', true],
  'BEMM': ['Belmont-sur-Montreux', true],
  'BEND': ['Bendlehn', true],
  'BENS': ['Bossonnens', true],
  'BER': ['Berlingen', true],
  'BERB': ['Beringen Bad Bf', true],
  'BERC': ['Bercher', true],
  'BERD': ['Beringerfeld', true],
  'BERG': ['Berg', true],
  'BESU': ['Bernina Suot', true],
  'BET': ['Bettlach', true],
  'BEV': ['Bever', true],
  'BEVE': ['Zufikon Belvédère', true],
  'BEVI': ['Bévieux', true],
  'BEWI': ['Berikon-Widen', true],
  'BEX': ['Bex', true],
  'BEXM': ['Bex-Place-du-Marché', true],
  'BF': ['Belfaux CFF', true],
  'BFV': ['Belfaux-Village', true],
  'BG': ['Brugg AG', true],
  'BGBI': ['Bibenlos-Sonnenhof', true],
  'BGG': ['Brügg BE', true],
  'BGH': ['Burghalden', true],
  'BGIS': ['Bremgarten Isenlauf', true],
  'BGL': ['Bürglen TG', true],
  'BGOT': ['Bremgarten Obertor', true],
  'BGVL': ['Brugg AG VL', false],
  'BGW': ['Bremgarten West', true],
  'BH': ['Burgholz', true],
  'BHOF': ['Burghof', false],
  'BI': ['Biel/Bienne', true],
  'BIA': ['Biasca', true],
  'BIB': ['Biberbrugg', true],
  'BIBD': ['Biel/Bienne Bözingenfeld/Champ', true],
  'BIBS': ['Biberist RBS', true],
  'BICA': ['Bière-Casernes', false],
  'BIER': ['Bière', true],
  'BIG': ['Biglen', true],
  'BIGE': ['Bigenthal', true],
  'BIGG': ['Biberegg', true],
  'BIGO': ['Biel (Goms)', true],
  'BIHO': ['Binzenhof', true],
  'BIL': ['Bilten', true],
  'BIM': ['Biel Mett', true],
  'BIOG': ['Bioggio', true],
  'BIOM': ['Bioggio Molinazzo', true],
  'BIPO': ['Biel Produktionsanlage Ost', false],
  'BIR': ['Birmensdorf ZH', true],
  'BIRB': ['Biel/Bienne RB', false],
  'BIRI': ['Birmensdorf Industrie', false],
  'BIRR': ['Birr', true],
  'BIST': ['Biberist Ost', true],
  'BITS': ['Bitsch', true],
  'BK': ['Brenzikofen', true],
  'BKI': ['Bätterkinden', true],
  'BLB': ['Blankenburg', true],
  'BLG': ['Baldegg', true],
  'BLGK': ['Baldegg Kloster', true],
  'BLIT': ['Boudry Littorail', true],
  'BLIZ': ['Blitzingen', true],
  'BLL': ['Ballwil', true],
  'BLN': ['Bleien Liebegg', true],
  'BLON': ['Blonay', true],
  'BLU': ['Blumenau', true],
  'BMA': ['Bauma', true],
  'BN': ['Bern', true],
  'BNAS': ['Bern Europaplatz', true],
  'BNB': ['Bern Brünnen Westside', true],
  'BNBS': ['Bern Bümpliz Süd', true],
  'BNBZ': ['Bern Bümpliz Nord', true],
  'BNFE': ['Bern Felsenau', true],
  'BNFI': ['Bern Fischermätteli', false],
  'BNG': ['Bussnang', true],
  'BNK': ['Benken SG', true],
  'BNTI': ['Bern Tiefenau', true],
  'BNWD': ['Bern Wankdorf', true],
  'BNWE': ['Bern Weissenbühl', true],
  'BNWF': ['Bern Wylerfeld', false],
  'BNWM': ['Bern Weyermannshaus', false],
  'BNZ': ['Benzenschwil', true],
  'BO': ['Bodio TI', true],
  'BOBO': ['Bossy Bois (embr)', false],
  'BODE': ['Boden', true],
  'BOEC': ['Le Boéchet', true],
  'BOIS': ['Les Bois', true],
  'BOLE': ['Bôle', true],
  'BOLI': ['Bolligen', true],
  'BOLL': ['Bollement', true],
  'BOLT': ['Boltigen', true],
  'BOMO': ['Bossy Moulins (embr)', false],
  'BON': ['Bonstetten-Wettswil', true],
  'BONA': ['Bonaduz', true],
  'BONF': ['Bonfol', true],
  'BONI': ['Boniswil', true],
  'BOS': ['Boswil-Bünzen', true],
  'BOSS': ['Bossière', true],
  'BOT': ['Bottighofen', true],
  'BOU': ['Bouveret', true],
  'BOUQ': ['Bouquetins', true],
  'BOUT': ['Boll-Utzigen', true],
  'BOVE': ['Bovernier', true],
  'BOW': ['Bowil', true],
  'BP': ['Belp', true],
  'BPST': ['Belp Steinbach', true],
  'BR': ['Brig', true],
  'BRA': ['Le Brassus', true],
  'BRAG': ['Bad Ragaz', true],
  'BRBA': ['Basel SBB RB Gr A', false],
  'BREG': ['Bremgarten', true],
  'BREL': ['Les Breuleux-Eglise', true],
  'BREN': ['Les Brenets', true],
  'BREU': ['Les Breuleux', true],
  'BRFL': ['Brunnenfluh', false],
  'BRG': ['Bargen BE', true],
  'BRIN': ['La Brinaz', true],
  'BRIO': ['Brusio', true],
  'BRIT': ['Brittnau-Wikon', true],
  'BRMG': ['Brig Bahnhofplatz', true],
  'BRN': ['Brunnadern-Neckertal', true],
  'BRNI': ['Brunni', false],
  'BRO': ['Bronschhofen', true],
  'BROA': ['Bronschhofen AMP', true],
  'BROF': ['Broc-Chocolaterie', true],
  'BROV': ['Broc-Village', true],
  'BRRA': ['Brig Autoverlad', true],
  'BRT': ['Bretonnières', true],
  'BRU': ['Brunnen', true],
  'BRUE': ['Brünig-Hasliberg', true],
  'BRUT': ['Brüttelen', true],
  'BRW': ['Brienzwiler', true],
  'BRZ': ['Brienz', true],
  'BRZW': ['Brienz West', true],
  'BS': ['Basel SBB', true],
  'BSBH': ['Birsfelden Hafen', false],
  'BSC': ['Bassecourt', true],
  'BSD': ['Bassersdorf', true],
  'BSDH': ['Basel Dreispitz', true],
  'BSFR': ['Basel Grenze (FR)', false],
  'BSGB': ['Basel SBB GB', false],
  'BSII': ['Basel SBB RB II', false],
  'BSJA': ['Basel St. Jakob', true],
  'BSJH': ['Basel St. Johann Hafen', false],
  'BSKH': ['Basel Kleinhüningen Hafen', false],
  'BSNK': ['Basel SBB RB Nordkopf (Abzw)', false],
  'BSRB': ['Basel SBB RB', false],
  'BSSJ': ['Basel St. Johann', true],
  'BSVB': ['Basel VB Grenze', false],
  'BT': ['Buttes', true],
  'BTH': ['Balsthal', true],
  'BTUI': ['Boudry Tuilière', true],
  'BTW': ['Bettwiesen', true],
  'BU': ['Buchs SG', true],
  'BUAG': ['Buchs AG', true],
  'BUB': ['Bubikon', true],
  'BUC': ['Buckten', true],
  'BUD': ['Buchs-Dällikon', true],
  'BUDI': ['Buchs-Dällikon Industrie', false],
  'BUDZ': ['Burgau Deponie ZAB (Agl)', false],
  'BUE': ['Bülach', true],
  'BUEH': ['Bühler', true],
  'BUER': ['Büren an der Aare', true],
  'BUET': ['Bütschwil', true],
  'BUGN': ['Bugnei', true],
  'BUHA': ['Buchhalde (Spw)', false],
  'BUHO': ['Büren zum Hof', true],
  'BUL': ['Bulle', true],
  'BULI': ['Buchli', true],
  'BURE': ['Bure-Casernes', false],
  'BURG': ['Burglauenen', true],
  'BURI': ['Burier', true],
  'BURN': ['Buchrain', true],
  'BUS': ['Busswil BE', true],
  'BUSM': ['Bussy-Chardonney', true],
  'BUZE': ['Buchs SG Zement', false],
  'BV': ['Bevaix', true],
  'BW': ['Beinwil am See', true],
  'BWA': ['Burgistein', true],
  'BWL': ['Birrwil', true],
  'BWY': ['Bern Wyler', false],
  'BWYW': ['Bern Wyler West (Abzw)', false],
  'BX': ['Buix', true],
  'BXPN': ['Bex Pont-Neuf', true],
  'BY': ['Bussigny', true],
  'BZN': ['Bischofszell Nord', true],
  'BZS': ['Bischofszell Stadt', true],
  'CAAG': ['Cappella-Agnuzzo', true],
  'CABA': ['Lancy-Bachet', true],
  'CABM': ['Chamby-Musée', true],
  'CABV': ['Monthey Centre agr Bas-V (embr', false],
  'CABY': ['Chamby', true],
  'CADE': ['Cadera', true],
  'CAIO': ['Campascio', true],
  'CAME': ['Camedo', true],
  'CAMP': ['Campocologno', true],
  'CAP': ['Capolago-Riva S. Vitale', true],
  'CASE': ['Les Cases', true],
  'CASI': ['Castione Impianto d\'inversione', false],
  'CASL': ['Caslano', true],
  'CASR': ['Castrisch', true],
  'CAST': ['Castione-Arbedo', true],
  'CAVA': ['Cavaglia', true],
  'CAVI': ['Cavigliano', true],
  'CAZI': ['Cazis', true],
  'CBY': ['Collombey', true],
  'CC': ['Concise', true],
  'CCH': ['Courchavon', true],
  'CD': ['Cadenazzo', true],
  'CDM': ['Champ-du-Moulin', true],
  'CDUE': ['Cavadürli', true],
  'CEF': ['Cery-Fleur-de-Lys', true],
  'CELE': ['Celerina', true],
  'CELS': ['Celerina Staz', true],
  'CF': ['La Chaux-de-Fonds', true],
  'CFES': ['La Chaux-de-Fonds-Est', true],
  'CFG': ['La Chaux-de-Fonds-Grenier', true],
  'CFO': ['La Chaux-de-Fonds Les Forges', true],
  'CFV': ['Courfaivre', true],
  'CG': ['Courgenay', true],
  'CGE': ['Montreux-Collège', true],
  'CGY': ['Cugy FR', true],
  'CH': ['Chur', true],
  'CHA': ['Chamoson-St-Pierre-de-Clages', true],
  'CHAA': ['Cham Alpenblick', true],
  'CHAB': ['Le Châble VS', true],
  'CHAC': ['Chardonney-Château', true],
  'CHAL': ['Châtelard VD', true],
  'CHAM': ['Cham', true],
  'CHAN': ['Chantemerle-près-Blonay', true],
  'CHAR': ['Charrat-Fully', true],
  'CHAT': ['Châtillens', true],
  'CHAU': ['La Chaudanne-Les Moulins', true],
  'CHAY': ['En Charnet', true],
  'CHB': ['Les Charbonnières', true],
  'CHBL': ['Château-de-Blonay', true],
  'CHCO': ['Chaulin-Cornaux', true],
  'CHE': ['Chénens', true],
  'CHEB': ['Chêne-Bourg', true],
  'CHER': ['Chernex', true],
  'CHES': ['Cheseaux', true],
  'CHET': ['Le Locle Le Chalet', true],
  'CHEV': ['Les Chevalleyres', true],
  'CHF': ['Châteauneuf-Conthey', true],
  'CHFR': ['Le Châtelard-Frontière', true],
  'CHGB': ['Chur GB', false],
  'CHGI': ['Le Châtelard VS', true],
  'CHGN': ['Chigny', true],
  'CHHO': ['Genève-Champel', true],
  'CHI': ['Chiasso', true],
  'CHIZ': ['La Chiésaz', true],
  'CHMO': ['La Chèvrerie-Monterêt', true],
  'CHN': ['Chambrelien', true],
  'CHOE': ['Château-d\'Oex', true],
  'CHS': ['Cheyres', true],
  'CHSA': ['Chur Altstadt', true],
  'CHSD': ['Châtel-St-Denis', true],
  'CHSM': ['Chiasso Smistamento', false],
  'CHTV': ['Château-d\'Hauteville', true],
  'CHV': ['Chavornay', true],
  'CHVI': ['Chavornay-Industrie', false],
  'CHWE': ['Chur West', true],
  'CHWI': ['Chur Wiesental', true],
  'CHX': ['Chexbres-Village', true],
  'CHXA': ['La Chaux-d\'Abel', true],
  'CHXB': ['La Chaux-des-Breuleux', true],
  'CHY': ['Chambésy', true],
  'CHZ': ['Choindez', false],
  'CIB': ['La Cibourg', true],
  'CIN': ['Cinuos-chel-Brail', true],
  'CL': ['Clarens', true],
  'CLA': ['Claro', false],
  'CLAI': ['La Clairière', true],
  'CLB': ['Colombier NE', true],
  'CLME': ['Chez-le-Maître-Ecoles', true],
  'CN': ['Corcelles-Nord', true],
  'CNAL': ['Colombier NE Allées Littorail', true],
  'CNLC': ['Colombier NE Les Chézards', true],
  'CNLI': ['Colombier NE Littorail', true],
  'CO': ['Cortébert', true],
  'COBA': ['La Corbatière', true],
  'COED': ['Les Coeudres-Est', true],
  'COEU': ['Les Coeudres', true],
  'COG': ['Corgémont', true],
  'COI': ['Vernier', true],
  'COL': ['Le Locle-Col-des-Roches', true],
  'COLB': ['Col-de-Bretaye', true],
  'COLS': ['Col-de-Soud', true],
  'COMB': ['La Combe', true],
  'COMS': ['Les Combes', true],
  'COMU': ['Collombey-Village', true],
  'COP': ['Coppet', true],
  'COR': ['Corbier', true],
  'CORA': ['Corcapolo', true],
  'CORC': ['Corcelles BE', true],
  'CORM': ['Cormoret', true],
  'CORN': ['Cornaux NE', true],
  'CORS': ['Corseaux-Cornalles', true],
  'COS': ['Cossonay-Penthalaz', true],
  'COT': ['Cottens FR', true],
  'COTA': ['Combe-Tabeillon', true],
  'COTD': ['Cottendart (embr)', false],
  'COU': ['La Cour', true],
  'COUR': ['Courtepin', true],
  'COUS': ['Cousset', true],
  'CP': ['Corcelles-Peseux', true],
  'CR': ['Croy-Romainmôtier', true],
  'CREB': ['Le Creux-des-Biches', true],
  'CREM': ['Crémines', true],
  'CRET': ['Le Crêt-du-Locle', true],
  'CRFR': ['Cressier FR', true],
  'CRGD': ['Creux-de-Genthod', true],
  'CRNE': ['Cressier NE', true],
  'CRY': ['Champéry', true],
  'CRYV': ['Champéry-Village', true],
  'CS': ['Corcelles-Sud', true],
  'CT': ['Court', true],
  'CTM': ['Courtemaîche', true],
  'CTT': ['Courtételle', true],
  'CTY': ['Courtelary', true],
  'CU': ['Cully', true],
  'CURE': ['La Cure', true],
  'CURT': ['Li Curt', true],
  'CV': ['Convers', false],
  'CVN': ['La Conversion', true],
  'CVTR': ['Couvet', true],
  'CXN': ['Croix-du-Nant', true],
  'DA': ['Dachsen', true],
  'DAD': ['Davos Dorf', true],
  'DAF': ['Davos Frauenkirch', true],
  'DAG': ['Dagmersellen', true],
  'DAGL': ['Davos Glaris', true],
  'DAIL': ['Daillens', false],
  'DAKO': ['Davos Kongress/Eisstadion', true],
  'DAL': ['Dallenwil', true],
  'DALT': ['Davos Laret', true],
  'DAM': ['Davos Monstein', true],
  'DAV': ['Davos Platz', true],
  'DAW': ['Davos Wolfgang', true],
  'DAY': ['Le Day', true],
  'DE': ['Domat/Ems', true],
  'DEI': ['Deisswil', true],
  'DEN': ['Denges-Echandens', true],
  'DENB': ['Denges B (bif)', false],
  'DER': ['Derendingen', false],
  'DEU': ['Les Deurres', true],
  'DG': ['Degersheim', true],
  'DI': ['Dielsdorf', true],
  'DIAB': ['Les Diablerets', true],
  'DIBE': ['Distelberg', true],
  'DIE': ['Diepflingen', true],
  'DIEN': ['Dieni', true],
  'DIH': ['Dinhard', true],
  'DIS': ['Disentis/Mustér', true],
  'DK': ['Däniken SO', true],
  'DKRB': ['Däniken RB', false],
  'DMT': ['Delémont', true],
  'DN': ['Deitingen', true],
  'DOE': ['Döttingen', true],
  'DOM': ['Domdidier', true],
  'DON': ['Dotzigen', true],
  'DOP': ['Dompierre FR', true],
  'DOR': ['Dornach-Arlesheim', true],
  'DORF': ['Dorfnest (Abzw)', false],
  'DOT': ['Dottikon-Dintikon', true],
  'DOTU': ['Dottikon Umspannanlage', false],
  'DOUY': ['La Douay', true],
  'DR': ['Därstetten', true],
  'DROT': ['Dürrenroth', true],
  'DSB': ['Diesbach-Betschwanden', true],
  'DSH': ['Diessenhofen', true],
  'DSTO': ['Dietikon Stoffelbach', true],
  'DT': ['Dietikon', true],
  'DTF': ['Dietfurt', true],
  'DTL': ['Dietlikon', true],
  'DTSS': ['Dietikon Schöneggstrasse', true],
  'DU': ['Dulliken', true],
  'DUE': ['Dübendorf', true],
  'DUED': ['Düdingen', true],
  'DUG': ['Duggingen', true],
  'EB': ['Eggerberg', true],
  'EBG': ['Engelberg', true],
  'EBI': ['Ebikon', true],
  'EBIS': ['Erlenbach im Simmental', true],
  'EBLI': ['Ebligen', true],
  'EBR': ['Emmenbrücke', true],
  'ECH': ['Echallens', true],
  'ECHE': ['Les Echenards', true],
  'ECL': ['Eclépens', true],
  'ECLS': ['Eclépens sud', false],
  'ECU': ['Ecublens-Rue', true],
  'EDA': ['Ennenda', true],
  'EDR': ['Les Esserts-de-Rive', true],
  'EF': ['Effretikon', true],
  'EFG': ['Effingen', false],
  'EG': ['Egerkingen', true],
  'EGG': ['Egg', true],
  'EGL': ['Eglisau', true],
  'EGN': ['Egnach', true],
  'EI': ['Eiken', true],
  'EIF': ['Eifeld', true],
  'EIGE': ['Eigerwand', true],
  'EIIE': ['Ei im Emmental', true],
  'EIS': ['Einsiedeln', true],
  'EISM': ['Eismeer', true],
  'EK': ['Ebnat-Kappel', true],
  'EL': ['Elgg', true],
  'EMB': ['Embrach-Rorbas', true],
  'EMI': ['Les Emibois', true],
  'EMM': ['Emmenmatt', true],
  'EMMA': ['Emmat', true],
  'EMSW': ['Domat/Ems Werk', true],
  'ENGE': ['Enge im Simmental', true],
  'ENN': ['Enney', true],
  'ENT': ['Entlebuch', true],
  'EP': ['Ependes VD', true],
  'EPS': ['Epesses', true],
  'ER': ['Erstfeld', true],
  'ERDM': ['Erdmannlistein', true],
  'ERL': ['Erlen', true],
  'ERLB': ['Erlenbach ZH', true],
  'ERM': ['Ermatingen', true],
  'ESB': ['Eschenbach LU', true],
  'ESCH': ['Escholzmatt', true],
  'ESEE': ['Ermensee', true],
  'ESL': ['Eschlikon TG', true],
  'ESP': ['Essert-Pittet', true],
  'ESSC': ['Essert-sous-Champvent', true],
  'ESSL': ['Esslingen', true],
  'EST': ['Estavayer-le-Lac', true],
  'ETA': ['Etagnières', true],
  'ETH': ['Ettenhausen-Emmetschloo', true],
  'ETIE': ['Etiez', true],
  'ETOY': ['Etoy', true],
  'EV': ['Evionnaz', true],
  'EVOU': ['Les Evouettes', true],
  'EW': ['Etzwilen', true],
  'EWMA': ['Ewil Maxon', true],
  'EX': ['Exergillod', true],
  'EYHO': ['Eyholz', true],
  'EZ': ['Eschenz', true],
  'FA': ['Faido', true],
  'FAY': ['Fayaux', true],
  'FAYO': ['Fayot', true],
  'FB': ['Feldbach', true],
  'FBG': ['Felsberg', true],
  'FBO': ['Fangboden', false],
  'FBR': ['Fraubrunnen', true],
  'FCH': ['Forch', true],
  'FCK': ['Frick', true],
  'FE': ['Felsenau AG', false],
  'FEB': ['Felsenburg', false],
  'FEBR': ['Feldbrunnen', true],
  'FEG': ['Ferenbalm-Gurbrü', true],
  'FEL': ['Felben-Wellhausen', true],
  'FER': ['La Ferrière', true],
  'FET': ['Fehraltorf', true],
  'FETI': ['Fehraltorf Industrie', false],
  'FEY': ['Fey', true],
  'FF': ['Frauenfeld', true],
  'FFMA': ['Frauenfeld Marktplatz', true],
  'FFPP': ['Frauenfeld Paketpost', false],
  'FG': ['Faoug', true],
  'FI': ['Fischenthal', true],
  'FID': ['Fideris', true],
  'FIE': ['Fiesch', true],
  'FIED': ['Fiesch Feriendorf', true],
  'FILI': ['Filisur', true],
  'FIN': ['Finhaut', true],
  'FL': ['Flüelen', true],
  'FLA': ['Flawil', true],
  'FLE': ['Fleurier', true],
  'FLED': ['Flendruz', true],
  'FLLE': ['Les Fontanelles', true],
  'FLM': ['Flamatt', true],
  'FLMD': ['Flamatt Dorf', true],
  'FLUM': ['Flumenthal', true],
  'FMS': ['Flums', true],
  'FON': ['Fontanivent', true],
  'FONT': ['Fontannaz-Seulaz', true],
  'FR': ['Frutigen', true],
  'FRAE': ['Fräschels', true],
  'FRB': ['Freienbach SBB', true],
  'FRBS': ['Freienbach SOB', true],
  'FRD': ['Ballens-Froideville', true],
  'FRE': ['Frenkendorf-Füllinsdorf', true],
  'FREC': ['Frenkendorf-F. Containerdepot', false],
  'FRET': ['Les Frêtes', true],
  'FRI': ['Fribourg/Freiburg', true],
  'FRIB': ['Zürich Friesenberg', true],
  'FRIN': ['Frinvillier-Taubenloch', true],
  'FRNP': ['Frutigen Nordportal (Abzw)', false],
  'FRPO': ['Fribourg/Freiburg Poya', true],
  'FSMF': ['Faido SMF', false],
  'FT': ['Feuerthalen', true],
  'FTAN': ['Ftan Baraigla', true],
  'FTY': ['Fontanney', true],
  'FU': ['Full', false],
  'FUER': ['Fürgangen-Bellwald Talstation', true],
  'FUM': ['Les Fumeaux', true],
  'FURN': ['Furna', true],
  'FYDM': ['Foyer Dents-du-Midi', true],
  'GA': ['Gampel-Steg', true],
  'GAE': ['Gänsbrunnen', true],
  'GAIS': ['Gais', true],
  'GAMS': ['Gamsen SBB', false],
  'GAS': ['Gasel', true],
  'GBA': ['Griesbach', true],
  'GBSG': ['St. Gallen Güterbahnhof', true],
  'GD': ['Arth-Goldau', true],
  'GDA': ['Gordola', true],
  'GDBE': ['Genthod-Bellevue', true],
  'GE': ['Genève', true],
  'GEAP': ['Genève-Aéroport', true],
  'GEC': ['Les Geneveys-sur-Coffrane', true],
  'GELF': ['Gelfingen', true],
  'GEN': ['Genolier', true],
  'GEPR': ['Genève-La-Praille', false],
  'GER': ['Gerra (Gambarogno)', true],
  'GERO': ['Gerolfingen', true],
  'GES': ['Geschinen', true],
  'GESE': ['Genève-Sécheron', true],
  'GEST': ['Genève-Stade', true],
  'GET': ['Gettnau', true],
  'GETG': ['Gettnau Güteranlage', false],
  'GEUE': ['Geuensee', false],
  'GEV': ['Genève-Eaux-Vives', true],
  'GEXI': ['Gexi', false],
  'GF': ['Glattfelden', true],
  'GFEL': ['Gfeld', true],
  'GH': ['Grosshöchstetten', true],
  'GI': ['Giswil', true],
  'GIB': ['Gibswil', true],
  'GIDI': ['Giustizia (dira)', false],
  'GIOC': ['Giornico (c bin)', false],
  'GIOV': ['Monthey Giovanola (embr)', false],
  'GIU': ['Giubiasco', true],
  'GIV': ['Givisiez', true],
  'GIVI': ['Givrins', true],
  'GIVR': ['La Givrine', true],
  'GKD': ['Gelterkinden', true],
  'GL': ['Glarus', true],
  'GLA': ['Gland', true],
  'GLB': ['Glattbrugg', true],
  'GLF': ['Gerlafingen', true],
  'GLO': ['Glovelier', true],
  'GLUR': ['Gluringen', true],
  'GLZB': ['Glanzenberg', true],
  'GM': ['Granges-Marnand', true],
  'GMM': ['Gümmenen', true],
  'GMOU': ['Grand-Moulin', true],
  'GN': ['Grenchen Nord', true],
  'GO': ['Goppenstein', true],
  'GOAR': ['Goppenstein Autoverlad', true],
  'GOE': ['Göschenen', true],
  'GOL': ['Goldach', true],
  'GON': ['Gontenschwil', true],
  'GONB': ['Gontenbad', true],
  'GONT': ['Gonten', true],
  'GOR': ['Gorgier-St-Aubin', true],
  'GOT': ['La Gottaz', true],
  'GP': ['Gampelen', true],
  'GRAC': ['Les Granges-Gérignoz', true],
  'GRAE': ['Gränichen', true],
  'GRAF': ['Grafenort', true],
  'GRAO': ['Gränichen Oberdorf', true],
  'GRAT': ['Gränichen Töndler', true],
  'GRBG': ['Gryon Bois-Gentil', true],
  'GRCH': ['Gryon-Chalméry', true],
  'GREL': ['Grellingen', true],
  'GREN': ['Grengiols', true],
  'GRES': ['Grésaley', true],
  'GRF': ['Grüenfeld', true],
  'GRIN': ['Grindelwald', true],
  'GRMA': ['Grünenmatt', true],
  'GRO': ['Grolley', true],
  'GRRI': ['Grafenried', true],
  'GRS': ['Grandson', true],
  'GRU': ['Grubenwald', true],
  'GRUB': ['Gruben', true],
  'GRUS': ['Grüsch', true],
  'GRV': ['Grandvaux', true],
  'GRVI': ['Villars-sous-Mont', true],
  'GRY': ['Gruyères', true],
  'GRYO': ['Gryon', true],
  'GS': ['Grenchen Süd', true],
  'GSAG': ['Emmenbrücke Gersag', true],
  'GSK': ['Gisikon-Root', true],
  'GSS': ['Gossau SG', true],
  'GSSO': ['Gossau-Sommerau (Agl)', false],
  'GST': ['Gstaad', true],
  'GT': ['Gammenthal', true],
  'GU': ['Gurtnellen', false],
  'GUA': ['Guarda', true],
  'GUBU': ['Gutenburg', true],
  'GUE': ['Gümligen', true],
  'GUET': ['Güttingen', true],
  'GUN': ['Guntershausen', true],
  'GVAL': ['Grandval', true],
  'GW': ['Gwatt', false],
  'GZ': ['Galmiz', true],
  'HA': ['Hasle-Rüegsau', true],
  'HAE': ['Hägendorf', true],
  'HAEW': ['Häggenschwil-Winden', true],
  'HAG': ['Haag-Gams', false],
  'HALD': ['Haldenstein', true],
  'HAMO': ['Häusernmoos', true],
  'HAMU': ['Hard-Mumenthal', true],
  'HAS': ['Hasle LU', true],
  'HB': ['Herzogenbuchsee', true],
  'HBK': ['Hindelbank', true],
  'HBRG': ['Hebrig', true],
  'HBTN': ['Hauenstein Nord (Spw)', false],
  'HBTS': ['Hauenstein Süd (Spw)', false],
  'HD': ['Hallwil', true],
  'HDK': ['Hendschiken', true],
  'HE': ['Herisau', true],
  'HEBG': ['Heerbrugg', true],
  'HEBR': ['Herbriggen', true],
  'HECK': ['Hagneck', true],
  'HED': ['Hedingen', true],
  'HEI': ['Heiden', true],
  'HEIN': ['Widen Heinrüti', true],
  'HEM': ['Hemishofen', true],
  'HEN': ['Henniez', true],
  'HERB': ['Herblingen', true],
  'HERL': ['Herrliberg-Feldmeilen', true],
  'HET': ['Hettlingen', true],
  'HG': ['Horgen', true],
  'HGO': ['Horgen Oberdorf', true],
  'HGT': ['Henggart', true],
  'HGV': ['Les Hauts-Geneveys', true],
  'HGW': ['Hergiswil NW', true],
  'HI': ['Hinwil', true],
  'HIK': ['Hitzkirch', true],
  'HINT': ['Hinteregg', true],
  'HIRS': ['Hirschberg', true],
  'HIT': ['Hirschthal', true],
  'HM': ['Hüttlingen-Mettendorf', true],
  'HMB': ['Heimberg', true],
  'HN': ['Horn', true],
  'HNS': ['Hornussen', false],
  'HO': ['Hochdorf', true],
  'HOBK': ['Holderbank AG', true],
  'HOEB': ['Höcklerbrücke', false],
  'HOND': ['Hondrich Süd', false],
  'HOS': ['Hospental', true],
  'HOSA': ['Hochdorf Schönau', true],
  'HOT': ['Horchental', false],
  'HPT': ['Hauptwil', true],
  'HRK': ['Härkingen Post', false],
  'HT': ['Hohtenn', true],
  'HTV': ['Hauteville', true],
  'HU': ['Hunzenschwil', true],
  'HUCH': ['Hünenberg Chämleten', true],
  'HUE': ['Hüswil', true],
  'HUER': ['Hürlistein (Abzw)', false],
  'HUEW': ['Hüntwangen-Wil', true],
  'HUR': ['Hurden', true],
  'HUSW': ['Hüswil West', false],
  'HUZY': ['Hünenberg Zythus', true],
  'HW': ['Horw', true],
  'HWIL': ['Huttwil', true],
  'HWSZ': ['Huttwil Sportzentrum', true],
  'HZH': ['Holzhäusern', true],
  'IGIS': ['Igis', true],
  'IL': ['Illnau', true],
  'ILZ': ['Ilanz', true],
  'IM': ['Immensee', true],
  'IMHO': ['Im Holz', true],
  'INN': ['Innertkirchen Kraftwerk (Bahn)', true],
  'INNP': ['Innertkirchen Grimseltor', true],
  'INS': ['Ins', true],
  'INSD': ['Ins Dorf', true],
  'INTR': ['Intragna', true],
  'INUN': ['Innertkirchen Unterwasser', true],
  'IO': ['Interlaken Ost', true],
  'IP': ['Ipsach', true],
  'IPHE': ['Ipsach Herdi', true],
  'ISL': ['Islikon', true],
  'ISLE': ['L\'Isle', true],
  'IT': ['Itingen', true],
  'ITT': ['Ittigen bei Bern', true],
  'IW': ['Interlaken West', true],
  'JAK': ['Jakobsbad', true],
  'JAZ': ['Jenaz', true],
  'JEG': ['Jegenstorf', true],
  'JO': ['Jona', true],
  'JOCL': ['Genolier clinique/campus', true],
  'JON': ['Jonction (Genève)', false],
  'JOR': ['Jor', true],
  'JOUM': ['Jouxtens-Mézery', true],
  'JTAL': ['Jakobstal', true],
  'KA': ['Kandersteg', true],
  'KAAG': ['Kaiserstuhl AG', true],
  'KAB': ['Kaltbrunn', true],
  'KABO': ['Kaltenboden (Agl)', false],
  'KAEP': ['Chäppeli', false],
  'KAHE': ['Kaltenherberg', true],
  'KAI': ['Kaiserstuhl OW', true],
  'KAL': ['Kallnach', true],
  'KALP': ['Kalpetran', true],
  'KARA': ['Kandersteg Autoverlad', true],
  'KAU': ['Kaiseraugst', true],
  'KB': ['Koblenz', true],
  'KBD': ['Koblenz Dorf', true],
  'KD': ['Kaufdorf', true],
  'KDI': ['Kleindietwil', true],
  'KE': ['Kemptthal', true],
  'KF': ['Konolfingen', true],
  'KGD': ['Küngoldingen', true],
  'KGO': ['Küsnacht Goldbach', true],
  'KH': ['Krattighalde', false],
  'KHF': ['Kehlhof', true],
  'KI': ['Kiesen', true],
  'KIAL': ['Kirchberg-Alchenflüh', true],
  'KIL': ['Kilchberg ZH', true],
  'KK': ['Kölliken', true],
  'KKO': ['Kölliken Oberdorf', true],
  'KL': ['Kloten', true],
  'KLB': ['Kloten Balsberg', true],
  'KLI': ['Klingnau', true],
  'KLO': ['Klosters Platz', true],
  'KLOD': ['Klosters Dorf', true],
  'KLUS': ['Klus', true],
  'KLW': ['Killwangen-Spreitenbach', true],
  'KMUE': ['Zug Chollermüli', true],
  'KN': ['Kempten', true],
  'KNO': ['Knonau', true],
  'KOE': ['Köniz', true],
  'KOL': ['Kollbrunn', true],
  'KPT': ['Kempraten', true],
  'KR': ['Kreuzlingen', true],
  'KRA': ['Kradolf', true],
  'KRB': ['Kreuzlingen Bernrain', true],
  'KREU': ['Kreuzstrasse', true],
  'KRH': ['Kreuzlingen Hafen', true],
  'KRM': ['Kriens Mattenhof', true],
  'KRU': ['Krummenau', true],
  'KS': ['Kehrsatz', true],
  'KSMD': ['Kölliken Sondermülldeponie', false],
  'KSN': ['Kehrsatz Nord', true],
  'KUE': ['Küssnacht am Rigi', true],
  'KUEB': ['Küblis', true],
  'KUES': ['Küsnacht ZH', true],
  'KURZ': ['Kurzrickenbach Seepark', true],
  'KWL': ['Kesswil', true],
  'KZ': ['Kerzers', true],
  'KZPP': ['Kerzers Papiliorama', true],
  'LA': ['Lachen SZ', true],
  'LADO': ['Langendorf', true],
  'LAED': ['Lädeli', true],
  'LAFA': ['La Faverge', true],
  'LAL': ['Lally', true],
  'LAM': ['Lamone-Cadempino', true],
  'LAN': ['Langwiesen', true],
  'LAPR': ['Lancy-Pont-Rouge', true],
  'LAPU': ['La Punt Chamues-ch', true],
  'LARG': ['La Large-Journée', true],
  'LAT': ['Lattigen bei Spiez', true],
  'LATR': ['Lattrigen', true],
  'LAUT': ['Lauterbrunnen', true],
  'LAV': ['Lavorgo', true],
  'LAVI': ['Lavin', true],
  'LAWI': ['Langwies GR', true],
  'LAX': ['Lax', true],
  'LB': ['Lenzburg', true],
  'LBAD': ['Leissigbad (Agl)', false],
  'LBD': ['Root D4', true],
  'LBF': ['Liebefeld', true],
  'LCR': ['Le Creux', false],
  'LD': ['Le Landeron', true],
  'LDS': ['Landschlacht', true],
  'LE': ['Leuzigen', false],
  'LEBO': ['Les Bovets', true],
  'LECH': ['Léchelles', true],
  'LEI': ['Leibstadt', false],
  'LEIM': ['Leimbach AG', true],
  'LEN': ['Lengnau BE', true],
  'LENG': ['Lengwil', true],
  'LENI': ['Les Nicolets', true],
  'LENK': ['Lenk im Simmental', true],
  'LES': ['Lessoc', true],
  'LEY': ['Leysin-Feydey', true],
  'LEYG': ['Leysin-Grand-Hôtel', true],
  'LEYV': ['Leysin-Village', true],
  'LF': ['Läufelfingen', true],
  'LFG': ['Laufenburg', true],
  'LFN': ['Laufen', true],
  'LG': ['Lugano', true],
  'LGB': ['Leuggelbach', true],
  'LGFL': ['Lugano FLP', true],
  'LGP': ['Paradiso', true],
  'LGV': ['Lugano Vedeggio', false],
  'LH': ['Lanzenhäusern', true],
  'LHE': ['La Heutte', true],
  'LHO': ['Lindenholz', true],
  'LIES': ['Langwies ZH', true],
  'LIEU': ['Le Lieu', true],
  'LIN': ['Linthal', true],
  'LINB': ['Linthal Braunwaldbahn', true],
  'LIT': ['Luzern Littau', true],
  'LITT': ['Litti (Baar)', false],
  'LITZ': ['Litzirüti', true],
  'LK': ['Leuk', true],
  'LL': ['Lalden', true],
  'LLA': ['La Lance (diag)', false],
  'LN': ['Langnau i.E.', true],
  'LNG': ['Langnau-Gattikon', true],
  'LO': ['Locarno', true],
  'LOAN': ['Locarno S. Antonio', true],
  'LOC': ['Le Locle', true],
  'LOCF': ['Le Locle-Frontière', false],
  'LOEW': ['Muntelier-Löwenberg', true],
  'LOLU': ['Lohn-Lüterkofen', true],
  'LOM': ['Lommiswil', true],
  'LON': ['Lonay-Préverenges', true],
  'LONA': ['Lonay A (bif)', false],
  'LONB': ['Lonay B (bif)', false],
  'LOTZ': ['Lotzwil', true],
  'LP': ['La Plaine', true],
  'LPN': ['Laupen BE', true],
  'LQ': ['Landquart', true],
  'LQRI': ['Landquart Ried', true],
  'LS': ['Lausanne', true],
  'LSA': ['La Sarraz', true],
  'LSAL': ['Les Salines', true],
  'LSB': ['Liesberg', false],
  'LSCH': ['Lausanne-Chauderon', true],
  'LSFL': ['Lausanne-Flon', true],
  'LSG': ['Lichtensteig', true],
  'LSN': ['Lausen', true],
  'LSSB': ['Lausanne-Sébeillon', false],
  'LST': ['Liestal', true],
  'LSTN': ['Liestal Nord (Abzw)', false],
  'LT': ['Lausanne-Triage', false],
  'LTAB': ['Lausanne-Triage A/B', false],
  'LTD': ['Lausanne-Triage D', false],
  'LTE': ['Lausanne-Triage Est', false],
  'LTG': ['Langenthal GB', false],
  'LTH': ['Langenthal', true],
  'LTHG': ['Langenthal Gaswerk', true],
  'LTHS': ['Langenthal Süd', true],
  'LTIN': ['Langenthal Industrie Nord', true],
  'LTSA': ['Lausanne-Triage SALT', false],
  'LTY': ['Lutry', true],
  'LU': ['Luchsingen-Hätzingen', true],
  'LUC': ['Lucens', true],
  'LUCA': ['Lüen-Castiel', true],
  'LUE': ['Lüsslingen', false],
  'LUED': ['Lüdem', true],
  'LUEL': ['Lütschental', true],
  'LUES': ['Lüscherz', true],
  'LUET': ['Lütisburg', true],
  'LUGO': ['Lützelflüh-Goldbach', true],
  'LUMU': ['Lustmühle', true],
  'LUN': ['Lungern', true],
  'LUPF': ['Lupfig', true],
  'LUT': ['Luterbach-Attisholz', true],
  'LUY': ['Lussy FR', false],
  'LVE': ['Le Verney (embr)', false],
  'LY': ['Lyss', true],
  'LYGR': ['Lyss Grien', true],
  'LYS': ['Lyssach', true],
  'LZ': ['Luzern', true],
  'LZGB': ['Luzern Cargo', false],
  'LZSH': ['Luzern Steghof (Abzw)', false],
  'LZVH': ['Luzern Verkehrshaus', true],
  'MA': ['Martigny', true],
  'MABC': ['Martigny-Bourg CT', false],
  'MABO': ['Martigny-Bourg', true],
  'MACR': ['Martigny-Croix', true],
  'MADI': ['Madiswil', true],
  'MADU': ['Madulain', true],
  'MAE': ['Märwil', true],
  'MAEG': ['Mägenwil', true],
  'MAEN': ['Männedorf', true],
  'MAER': ['Märstetten', true],
  'MAG': ['Magadino-Vira', true],
  'MAGL': ['Magliaso', true],
  'MAGP': ['Magliaso Paese', true],
  'MAIF': ['Maiacher', true],
  'MAL': ['Malters', true],
  'MALA': ['Malans GR', true],
  'MALU': ['Martigny Aluminium (embr)', false],
  'MAM': ['Mammern', true],
  'MANE': ['Le Manège', true],
  'MANN': ['Mannenbach-Salenstein', true],
  'MAR': ['Maroggia-Melano', true],
  'MARA': ['Le Marais', true],
  'MARE': ['Les Marécottes', true],
  'MAS': ['Massongex', true],
  'MATA': ['Mattstetten (Abzw)', false],
  'MATE': ['Matten i.S.', true],
  'MATT': ['Hergiswil Matt', true],
  'MATZ': ['Matzingen', true],
  'MAU': ['Menznau', true],
  'MAUZ': ['Mauraz', true],
  'MAXP': ['Martigny-Expo', true],
  'MB': ['Malleray-Bévilard', true],
  'MBI': ['Matten b. Interlaken', true],
  'MD': ['Moudon', true],
  'MDE': ['Melide', true],
  'ME': ['Menziken', true],
  'MED': ['La Médettaz', true],
  'MEG': ['Meggen', true],
  'MEGZ': ['Meggen Zentrum', true],
  'MEL': ['Mellingen', false],
  'MELH': ['Mellingen Heitersberg', true],
  'MELN': ['Mellikon', true],
  'MELS': ['Mels', true],
  'MEN': ['Mendrisio', true],
  'MEP': ['Marin-Epagnier', true],
  'MERL': ['Merlischachen', true],
  'MEZ': ['Mezzovico', true],
  'MF': ['Maienfeld', true],
  'MG': ['Murg', true],
  'MGEN': ['Mörigen', true],
  'MGT': ['Murgenthal', true],
  'MH': ['Mühlehorn', true],
  'MHN': ['Mittelhäusern', true],
  'MI': ['Muri AG', true],
  'MIES': ['Mies', true],
  'MINU': ['Minusio', true],
  'MIRA': ['Miralago', true],
  'MIT': ['Mitlödi', true],
  'MKR': ['Meierskappel-Risch', false],
  'ML': ['Meilen', true],
  'MM': ['Müntschemier', true],
  'MMUH': ['Mittelmuhen', true],
  'MO': ['Mosen', true],
  'MOE': ['Möhlin', true],
  'MOEL': ['Mörel', true],
  'MOER': ['Mörschwil', true],
  'MOG': ['Mogelsberg', true],
  'MOOS': ['Moos', true],
  'MOR': ['Morges', true],
  'MORI': ['Montricher', true],
  'MOSE': ['Moosseedorf', true],
  'MOSM': ['Mendrisio S. Martino', true],
  'MOT': ['Môtiers NE', true],
  'MOTA': ['Morteratsch', true],
  'MOTU': ['Mumpé Tujetsch', true],
  'MOU': ['Moutier', true],
  'MPF': ['Mumpf', true],
  'MR': ['Meiringen', true],
  'MRAB': ['Meiringen Alpbach', true],
  'MRL': ['Moreillon', true],
  'MROS': ['Täsch Monte Rosa', true],
  'MRSS': ['Aareschlucht West', true],
  'MRT': ['Murten/Morat', true],
  'MS': ['Münsingen', true],
  'MSCH': ['Münsterlingen-Scherzingen', true],
  'MSPI': ['Münsterlingen Spital', true],
  'MST': ['Münchenstein', true],
  'MTB': ['Montbovon', true],
  'MTH': ['Monthey', true],
  'MTHH': ['Monthey-Hôpital', true],
  'MTHP': ['Monthey-En Place', true],
  'MTHV': ['Monthey-Ville', true],
  'MTL': ['Marthalen', true],
  'MTLN': ['Marthalen Nord', false],
  'MTM': ['Mettmenstetten', true],
  'MTR': ['Matran', true],
  'MU': ['Muttenz', true],
  'MUAU': ['Muriaux', true],
  'MUCO': ['Münchenwiler-Courgevaux', true],
  'MUE': ['Mülenen', true],
  'MUEB': ['Münchenbuchsee', true],
  'MUEH': ['Mühlau', true],
  'MUEL': ['Müllheim-Wigoltingen', true],
  'MUER': ['Mürren BLM', true],
  'MUET': ['Münster VS', true],
  'MUH': ['Muhen', true],
  'MUHN': ['Muhen Nord', true],
  'MUI': ['Le Muids', true],
  'MUND': ['Mundbach (Spw)', false],
  'MUO': ['Muolen', true],
  'MUSS': ['Mussachen', true],
  'MWIL': ['Münchwilen TG', true],
  'MX': ['Montreux', true],
  'NAEF': ['Näfels-Mollis', true],
  'NAEN': ['Nänikon-Greifensee', true],
  'NAET': ['Nätschen', true],
  'NB': ['Niederbipp', true],
  'NBD': ['Niederbipp Dorf', true],
  'NBT': ['Niederbottigen BN', false],
  'NE': ['Neuchâtel', true],
  'NEB': ['Nebikon', true],
  'NECB': ['Neuchâtel Champ-Bougin', true],
  'NEFD': ['Neuchâtel Cargo', false],
  'NEIR': ['Neirivue', true],
  'NELI': ['Neuchâtel Evole', true],
  'NEMA': ['Neuchâtel Est (bif)', false],
  'NEPS': ['Neuchâtel Port-de-Serrières', true],
  'NESE': ['Neuchâtel-Serrières', true],
  'NET': ['Netstal', true],
  'NEU': ['Neuthal', true],
  'NEUK': ['Neunkirch', true],
  'NEY': ['Neyruz FR', true],
  'NEYS': ['Les Neys', true],
  'NFCH': ['Neue Forch', true],
  'NG': ['Niederglatt ZH', true],
  'NGG': ['Neuenegg', true],
  'NGR': ['Neugrüt (Verzw)', false],
  'NH': ['Neuhausen', true],
  'NHB': ['Neuhausen Bad Bf', true],
  'NHBH': ['Neuhaus bei Hinteregg', true],
  'NHGR': ['Neuhausen Grenze DB', false],
  'NHOF': ['Neuenhof', true],
  'NHRH': ['Neuhausen Rheinfall', true],
  'NIBE': ['Nidau Beunden', true],
  'NID': ['Nidfurn-Haslen', true],
  'NIDA': ['Nidau', true],
  'NIE': ['Niederhasli', true],
  'NIIN': ['Niederbipp Industrie', true],
  'NK': ['Neukirch-Egnach', true],
  'NL': ['Nesslau-Neu St. Johann', true],
  'NM': ['Neumühle', true],
  'NO': ['Nottwil', true],
  'NOGG': ['St. Gallen Notkersegg', true],
  'NOI': ['Noiraigue', true],
  'NOMO': ['Le Noirmont', true],
  'NOU': ['Nieder- und Oberurnen', true],
  'NPLI': ['Neuchâtel Place Pury Littorail', true],
  'NR': ['Niederried', true],
  'NRRB': ['Niederrickenbach Station', true],
  'NS': ['Niederscherli', true],
  'NSRL': ['Neuchâtel Serrières Ruau', true],
  'NTEU': ['Niederteufen', true],
  'NV': ['La Neuveville', true],
  'NW': ['Niederweningen', true],
  'NWA': ['Niederwangen', true],
  'NWAL': ['Niederwald', true],
  'NWD': ['Niederweningen Dorf', true],
  'NY': ['Nyon', true],
  'OA': ['Oberaach', true],
  'OAB': ['Oberried am Brienzersee', true],
  'OB': ['Oberbuchsiten', true],
  'OBAL': ['Oberalppass', true],
  'OBB': ['Oberburg', true],
  'OBBI': ['Oberbipp', true],
  'OBEI': ['Oberei bei Wasen i.E.', true],
  'OBGE': ['Obergesteln', true],
  'OBK': ['Oberkirch LU', true],
  'OBW': ['Oberwald', true],
  'OBWAT': ['Oberwald Autoverlad', true],
  'OBZO': ['Oberzollikofen', true],
  'OD': ['Oberdiessbach', true],
  'ODF': ['Oberdorf SO', true],
  'OE': ['Oey-Diemtigen', true],
  'OEF': ['Oberentfelden', true],
  'OEFU': ['Oberentfelden Uerkenbrücke', true],
  'OEFW': ['Oberentfelden Engelplatz', true],
  'OEN': ['Oensingen', true],
  'OES': ['Oeschseite', true],
  'OF': ['Otelfingen', true],
  'OFI': ['Otelfingen Industrie', false],
  'OFR': ['Otelfingen Golfpark', true],
  'OGL': ['Oberglatt ZH', true],
  'OI': ['Oberrüti', true],
  'OIS': ['Oberwil im Simmental', true],
  'OKU': ['Oberkulm', true],
  'OL': ['Olten', true],
  'OLH': ['Olten Hammer', true],
  'OLLO': ['Ollon VD', true],
  'OLRB': ['Olten RB', false],
  'OLTU': ['Olten Tunnel (Spw)', false],
  'OMUH': ['Obermuhen', true],
  'ONB': ['Onnens-Bonvillars', false],
  'ONBP': ['Onnens-Bonvillars PMP', false],
  'OND': ['Ondallaz-L\'Alliaz', true],
  'OP': ['Opfikon', true],
  'OPP': ['Oppikon', true],
  'OPS': ['Opfikon Süd', false],
  'OR': ['Oron', true],
  'ORD': ['Oberrieden', true],
  'ORDD': ['Oberrieden Dorf', true],
  'ORIN': ['Orbe-Industrie (marchandises)', false],
  'ORS': ['Orsières', true],
  'ORT': ['Oberriet SG', true],
  'OS': ['Osogna-Cresciano', false],
  'OSBE': ['Ospizio Bernina', true],
  'OSS': ['Ossingen', true],
  'OST': ['Ostermundigen', true],
  'OTH': ['Othmarsingen', true],
  'OWA': ['Oberwangen', true],
  'OWT': ['Oberwinterthur', true],
  'PAL': ['Palézieux', true],
  'PALG': ['Palagnedra', true],
  'PALV': ['Palézieux-Village', true],
  'PALZ': ['Château-d\'Oex La Palaz', true],
  'PAPI': ['Papiermühle', true],
  'PAQ': ['Le Pâquier-Montbarry', true],
  'PASE': ['Pampigny-Sévery', true],
  'PASQ': ['Pasquerio (bin rac)', false],
  'PAY': ['Payerne', true],
  'PDM': ['Les Ponts-de-Martel', true],
  'PDS': ['Les Paluds', false],
  'PEI': ['Peist', true],
  'PEN': ['Pensier', true],
  'PF': ['Pfäffikon SZ', true],
  'PFAF': ['Pfaffensprung (Spw)', false],
  'PFL': ['Münchwilen Pflegeheim', true],
  'PFU': ['Pfungen', true],
  'PFZ': ['Pfäffikon ZH', true],
  'PIE': ['Pieterlen', true],
  'PIEO': ['Le Pied-d\'Or', true],
  'PLAC': ['Planchamp', true],
  'PLAM': ['Plambuit', true],
  'PLAN': ['Les Plantaz', true],
  'PLAS': ['Les Planches (Aigle)', true],
  'PLEI': ['Les Pléiades', true],
  'PLMO': ['Plan Morier', true],
  'POBR': ['Ponte Brolla', true],
  'POFA': ['Pont de Fayot', true],
  'POLD': ['Pollegio Sud (Dira)', false],
  'POLL': ['Pollegio', false],
  'POLN': ['Pollegio Nord (dira)', false],
  'POLS': ['Pollegio binario di sorpasso', false],
  'PON': ['Pontenet', true],
  'POR': ['Porrentruy', true],
  'PORE': ['Pontresina', true],
  'POS': ['Poschiavo', true],
  'POSS': ['Les Posses', true],
  'POTR': ['Ponte Tresa', true],
  'POZZ': ['Pozzo Negro (dira)', false],
  'PR': ['Pratteln', true],
  'PRAL': ['Les Pralies', true],
  'PRCH': ['Prilly-Chasseur', true],
  'PRED': ['Preda', true],
  'PREP': ['Pré-Petitjean', true],
  'PRES': ['Le Prese', true],
  'PRL': ['Prélionne', true],
  'PRLZ': ['Prélaz-sur-Blonay', true],
  'PRMA': ['Prilly-Malley', true],
  'PRSR': ['Pratteln Salina Raurica', true],
  'PRST': ['La Presta Mines d\'asphalte', true],
  'PRUW': ['Pratteln Ueberwerfung', false],
  'PT': ['Le Pont', true],
  'PTC': ['Pont-Céard', true],
  'PTD': ['Pont-de-Drapel', true],
  'PTM': ['Punt Muragl', true],
  'PTMA': ['Petit-Martel', true],
  'PTME': ['Petit-Martel-Est', true],
  'PTMS': ['Punt Muragl Staz', true],
  'PTR': ['Pont du Rhône', true],
  'PU': ['Pully', true],
  'PUI': ['Puidoux', true],
  'PUN': ['Pully-Nord', true],
  'QUA': ['Quartino', true],
  'RA': ['Ramsen', true],
  'RAET': ['Räterschen', true],
  'RAM': ['Ramsei', true],
  'RAND': ['Randa', true],
  'RAR': ['Raron', true],
  'RARK': ['Rarnerkumme (Spw)', false],
  'RASU': ['Rabius-Surrein', true],
  'RBA': ['Rohrbach', true],
  'RBG': ['Rothenburg Station', true],
  'RBGD': ['Emmenbrücke Kapf', true],
  'RBL': ['Zürich RB Limmattal', false],
  'RBLA': ['RBL A-Gruppe', false],
  'RBLP': ['Zürich RB Limmattal Depot/Bau', false],
  'RCH': ['Bern Riedbach', true],
  'RCHG': ['Roches Grises', true],
  'RCK': ['Rheineck', true],
  'RCY': ['Le Rocheray', true],
  'RDM': ['Riedmatt SZ', true],
  'RE': ['Renan BE', true],
  'REAL': ['Realp', true],
  'REALAT': ['Realp Autoverlad', true],
  'REAZ': ['Rennaz (Leysin)', true],
  'REB': ['Rebstein-Marbach', true],
  'REC': ['Reconvilier', true],
  'RECK': ['Reckingen VS', true],
  'REG': ['Regensdorf-Watt', true],
  'REI': ['Reinach AG', true],
  'REID': ['Reiden', true],
  'REIF': ['Reichenau Farsch (Abzw)', false],
  'REIK': ['Reichenbach im Kandertal', true],
  'REIN': ['Reinach AG Nord', true],
  'REIT': ['Reichenau-Tamins', true],
  'REK': ['Rekingen AG', true],
  'RELP': ['Renens VD Larges Pièces (embr)', false],
  'REMA': ['Remaufens', true],
  'REMI': ['Reinach AG Mitte', true],
  'REN': ['Renens VD', true],
  'RENB': ['Renens VD Est (bif)', false],
  'RENE': ['Renens VD Entrepôts', false],
  'RENO': ['Renens VD Ouest (bif)', false],
  'REPP': ['Reppischhof', true],
  'REU': ['Reuchenette-Péry', true],
  'REUS': ['Les Reussilles', true],
  'REUT': ['Reutlingen', true],
  'REV': ['Reverolle', true],
  'REYM': ['Le Reymond', true],
  'RF': ['Rheinfelden', true],
  'RFAU': ['Rheinfelden Augarten', true],
  'RG': ['Reichenburg', true],
  'RGD': ['Ringoldingen', true],
  'RH': ['Romanshorn', true],
  'RHAE': ['Rhäzüns', true],
  'RHGB': ['Romanshorn GB', false],
  'RI': ['Richterswil', true],
  'RIAZ': ['Riazzino', true],
  'RIB': ['Rivera-Bironico', true],
  'RID': ['Riddes', true],
  'RIEB': ['Riehen', true],
  'RIET': ['Rietheim', true],
  'RIHO': ['Riedholz', true],
  'RIK': ['Rickenbach-Attikon', true],
  'RILI': ['Ringlikon', true],
  'RIN': ['Ringgenberg', true],
  'RINZ': ['Riehen Niederholz', true],
  'RIPE': ['Les Ripes', true],
  'RITH': ['St. Gallen Riethüsli', true],
  'RITI': ['Rietli', true],
  'RIV': ['Rivaz', true],
  'RK': ['Rotkreuz', true],
  'RLG': ['Rümlingen', true],
  'RMZ': ['Rämismühle-Zell', true],
  'RN': ['Rikon', true],
  'RO': ['Rodi-Fiesso', false],
  'ROBG': ['Roggwil-Berg', true],
  'ROBU': ['Roggwil Buchägerten', true],
  'ROC': ['Roche VD', true],
  'ROG': ['Roggwil-Wynau', true],
  'ROGD': ['Roggwil Dorf', true],
  'ROL': ['Rolle', true],
  'ROM': ['Romont FR', true],
  'RORE': ['Rodels-Realta', true],
  'ROS': ['Rosé', true],
  'ROSC': ['Roggwil Schmitten', true],
  'ROSI': ['Rossinière', true],
  'ROSL': ['Romanel-sur-Lausanne', true],
  'ROSS': ['Rosshäusern', true],
  'ROTH': ['Rothenbrunnen', true],
  'ROU': ['Rougemont', true],
  'ROUL': ['La Roulaz', true],
  'RS': ['Rorschach', true],
  'RSGB': ['Rorschach GB', false],
  'RSHF': ['Rorschach Hafen', true],
  'RSST': ['Rorschach Stadt', true],
  'RT': ['Riet (Verzw)', false],
  'RTAL': ['Rosental', true],
  'RTEM': ['Route de Morgins', true],
  'RTH': ['Rüthi SG', true],
  'RTI': ['Rüti bei Büren', false],
  'RTR': ['Rothrist', true],
  'RTRH': ['Rothrist GB', false],
  'RTT': ['Rothenthurm', true],
  'RTW': ['Riedtwil', false],
  'RU': ['Rupperswil', true],
  'RUAZ': ['La Ruaz', true],
  'RUB': ['Rubigen', true],
  'RUD': ['Rudolfstetten', true],
  'RUDB': ['Ruderbach', true],
  'RUE': ['Rüti ZH', true],
  'RUEM': ['Rümlang', true],
  'RUEN': ['Rümikon AG', true],
  'RUER': ['Rueras', true],
  'RUES': ['Rüschlikon', true],
  'RUET': ['Rüti GL', true],
  'RUEU': ['Rueun', true],
  'RUHO': ['Rudolfstetten Hofacker', true],
  'RUS': ['Russin', true],
  'RW': ['Rapperswil SG', true],
  'RYAB': ['Rynächt (Abzw)', false],
  'RYN': ['Rynächt Nord', false],
  'RYUE': ['Rynächt Ueberholgleisanlage', false],
  'RZ': ['Rafz', true],
  'RZO': ['Ranzo-S. Abbondio', true],
  'SA': ['Sargans', true],
  'SAAC': ['Sandacher (Spw)', false],
  'SAAN': ['Saanen', true],
  'SAAS': ['Saas im Prättigau', true],
  'SAAV': ['Sagliains Autoverlad', true],
  'SACH': ['Sachseln', true],
  'SAEG': ['La Sagne-Eglise', true],
  'SAF': ['Safenwil', true],
  'SAGL': ['Sagliains', true],
  'SAGN': ['La Sagne', true],
  'SAIG': ['Saignelégier', true],
  'SAL': ['Salgesch', true],
  'SALE': ['Sâles', false],
  'SAM': ['Samstagern', true],
  'SAME': ['Samedan', true],
  'SAMO': ['Saanenmöser', true],
  'SAN': ['S. Antonino', true],
  'SAPL': ['Sammelplatz', true],
  'SAR': ['Sarnen', true],
  'SAS': ['Salez-Sennwald', true],
  'SASL': ['Sargans Schleife (Verzw)', false],
  'SAT': ['Sattel-Aegeri', false],
  'SATT': ['Sattel', true],
  'SAX': ['Saxon', true],
  'SB': ['Sandbüchel', true],
  'SBA': ['Steigbach', true],
  'SBAD': ['Schinznach Bad', true],
  'SBAR': ['Schwarzer Bären', true],
  'SBG': ['Sihlbrugg', false],
  'SBL': ['St-Blaise CFF', true],
  'SBLB': ['St-Blaise-Lac', true],
  'SBN': ['Subingen', false],
  'SBR': ['Schwarzwasserbrücke', true],
  'SCAE': ['Schänis', true],
  'SCAN': ['S-chanf', true],
  'SCB': ['Sonceboz-Sombeval', true],
  'SCBG': ['Schwarzenburg', true],
  'SCBS': ['Schönbühl RBS', true],
  'SCBU': ['Schübelbach-Buttikon', true],
  'SCDE': ['Schwende', true],
  'SCEA': ['Schachen (Gais)', true],
  'SCGR': ['Schmitten GR Landwasserviadukt', true],
  'SCH': ['Schachen (Herisau)', true],
  'SCHA': ['Schachen LU', true],
  'SCHB': ['Schönbühl SBB', true],
  'SCHD': ['Schwanden GL', true],
  'SCHF': ['Schöftland', true],
  'SCHH': ['Schüpfheim', true],
  'SCHI': ['Schindellegi-Feusisberg', true],
  'SCHK': ['Schottikon', true],
  'SCHL': ['Schlieren', true],
  'SCHN': ['Schlattingen', true],
  'SCHO': ['Schöfflisdorf-Oberweningen', true],
  'SCHT': ['Schlatt TG', true],
  'SCHW': ['Schwyz', true],
  'SCHZ': ['Schwarzenbach SG', false],
  'SCI': ['Les Sciernes', true],
  'SCLC': ['St-Cergue Les Cheseaux', true],
  'SCME': ['Schmerikon', true],
  'SCMI': ['Schmitten FR', true],
  'SCN': ['Schalunen', true],
  'SCNW': ['Schöftland Nordweg', true],
  'SCOE': ['Schönenwerd SO', true],
  'SCOO': ['Schönenwerd SO Ost (Spw)', false],
  'SCR': ['Schönried', true],
  'SCRN': ['Scheuren', true],
  'SCRS': ['Schiers', true],
  'SCSH': ['Schönbühl Shoppyland', true],
  'SCTA': ['Scuol-Tarasp', true],
  'SCUE': ['Schüpfen', true],
  'SCWE': ['Schwerzenbach ZH', true],
  'SD': ['Saland', true],
  'SDO': ['Schinznach Dorf', false],
  'SDY': ['Sendy-Sollard', true],
  'SE': ['Seon', true],
  'SEC': ['Le Séchey', true],
  'SED': ['Sedrun', true],
  'SEEB': ['Seebleiche', true],
  'SEEV': ['Seewis-Pardisla', true],
  'SEG': ['Segnas', true],
  'SEL': ['Selzach', true],
  'SELF': ['Klosters Selfranga', true],
  'SEM': ['Sempach-Neuenkirch', true],
  'SEMB': ['Sembrancher', true],
  'SEMS': ['Semsales', true],
  'SEN': ['Le Sentier-L\'Orient', true],
  'SENO': ['Seon Nord', true],
  'SEP': ['Le Sépey', true],
  'SERN': ['Serneus', false],
  'SERO': ['Serocca', true],
  'SETB': ['Sumiswald-Grünen ETB', false],
  'SEU': ['Seuzach', true],
  'SEV': ['Sevelen', true],
  'SEVA': ['Sévaz (embr)', false],
  'SF': ['Seftigen', true],
  'SFM': ['S-chanf Marathon', true],
  'SG': ['St. Gallen', true],
  'SGAR': ['Schützengarten', true],
  'SGBI': ['St. Gallen Birnbäumen', true],
  'SGBR': ['St. Gallen Bruggen', true],
  'SGF': ['St. Gallen St. Fiden', true],
  'SGGB': ['St. Gallen GB', false],
  'SGHA': ['St. Gallen Haggen', true],
  'SGMP': ['St. Gallen Marktplatz', true],
  'SGO': ['Le Solliat-La Golisse', true],
  'SGWI': ['St. Gallen Winkeln', true],
  'SH': ['Schaffhausen', true],
  'SHAL': ['Schweizerhalle', false],
  'SHAU': ['Siegershausen', true],
  'SHF': ['Zürich Schweighof', true],
  'SHIE': ['Schafhausen i.E.', true],
  'SHNO': ['Schaffhausen Nord', false],
  'SHRB': ['Schaffhausen GB', false],
  'SHS': ['St. Gallen Schülerhaus', true],
  'SHSU': ['Schaffhausen Süd', false],
  'SIA': ['Sihlau', true],
  'SIB': ['Siebnen-Wangen', true],
  'SIE': ['Sierre/Siders', true],
  'SIFI': ['Siselen-Finsterhennen', true],
  'SIG': ['Siggenthal-Würenlingen', true],
  'SIGI': ['Sigirino', false],
  'SIGN': ['Signau', true],
  'SILB': ['Silberen (Abzw)', false],
  'SILS': ['Sils im Domleschg (Abzw)', false],
  'SINS': ['Sins', true],
  'SIO': ['Sion', true],
  'SIPO': ['Siporex (embr)', false],
  'SIR': ['Sirnach', true],
  'SIS': ['Sissach', true],
  'SIT': ['Sitterdorf', true],
  'SIW': ['Sihlwald', true],
  'SIXF': ['Six-Fontaines', true],
  'SK': ['Sisikon', true],
  'SKY': ['Sennhof-Kyburg', true],
  'SL': ['St-Léonard', true],
  'SLB': ['Sur-le-Buis', true],
  'SLF': ['Schloss Laufen am Rheinfall', true],
  'SLG': ['Sulgen', true],
  'SLN': ['Sisseln', false],
  'SLV': ['Salvan', true],
  'SM': ['St-Maurice', true],
  'SMAR': ['Solduno S. Martino', true],
  'SMG': ['St. Margrethen SG', true],
  'SMOR': ['St. Moritz', true],
  'SN': ['S. Nazzaro', true],
  'SNAG': ['Scharnageln', true],
  'SNK': ['St. Niklaus VS', true],
  'SO': ['Solothurn', true],
  'SOAD': ['Solothurn Allmend', true],
  'SOBT': ['Solothurn Baseltor', true],
  'SOGO': ['Sorengo', true],
  'SOLD': ['Solduno', true],
  'SOM': ['Sommerau', true],
  'SONZ': ['Sonzier', true],
  'SOOD': ['Sood-Oberleimbach', true],
  'SOR': ['Sorvilier', true],
  'SORL': ['Sorengo Laghetto', true],
  'SOST': ['Solothurn Sternen', true],
  'SOY': ['Soyhières', false],
  'SP': ['Spiez', true],
  'SPAB': ['Spiez (Abzw)', false],
  'SPAO': ['Bellinzona S. Paolo', false],
  'SPEI': ['Speicher', true],
  'SPIN': ['Spinas', true],
  'SPIS': ['St. Gallen Spisertor', true],
  'SPIT': ['Spital Zollikerberg', true],
  'SPMS': ['Spiezmoos Süd', false],
  'SRND': ['Sarnen Nord', true],
  'SROC': ['Sur Roche', true],
  'SS': ['Sursee', true],
  'SSMF': ['Sedrun SMF', false],
  'SSP': ['St-Sulpice NE', true],
  'SST': ['Schnaus-Strada', false],
  'SSTA': ['Stansstad', true],
  'SSWM': ['Sursee Wassermatte', false],
  'ST': ['St-Triphon', false],
  'STA': ['Staad SG', true],
  'STAE': ['Stäfa', true],
  'STAF': ['Stabio', true],
  'STAL': ['Stalden i.E.', true],
  'STAN': ['Stans', true],
  'STAO': ['Stabio Cargo', false],
  'STAS': ['Stalden-Saas', true],
  'STB': ['Steinebrunn', true],
  'STBA': ['Steinibach', true],
  'STBG': ['Steinerberg', true],
  'STCE': ['St-Cergue', true],
  'STCH': ['Steinach', true],
  'STCR': ['Ste-Croix', true],
  'STD': ['Le Stand', true],
  'STE': ['Steinhausen', true],
  'STEE': ['Steinegg', true],
  'STEF': ['Steffisburg', true],
  'STEL': ['St-Eloi', true],
  'STER': ['St. Erhard-Knutwil', true],
  'STET': ['Stettbach', true],
  'STFE': ['Teufen AR Stofel', true],
  'STG': ['Steg', true],
  'STGE': ['St. German (Abzw)', false],
  'STGI': ['St-Gingolph (Suisse)', true],
  'STGR': ['St-Triphon-Gare', true],
  'STI': ['St-Imier', true],
  'STJ': ['Morges-St-Jean', true],
  'STK': ['Steckborn', true],
  'STKA': ['St. Katharinen', true],
  'STKT': ['St. Katharinental', true],
  'STLE': ['St-Légier-Gare', true],
  'STLS': ['St-Triphon Lessus', false],
  'STLV': ['St-Légier-Village', true],
  'STM': ['Stammheim', true],
  'STMR': ['Steinmaur', true],
  'STN': ['Steinen', true],
  'STOI': ['Stöckli', true],
  'STOS': ['Stoss AR', true],
  'STP': ['St-Prex', true],
  'STPM': ['St. Peter-Molinis', true],
  'STR': ['Stein am Rhein', true],
  'STRH': ['Strahlholz', true],
  'STRI': ['Steinhausen Rigiblick', true],
  'STS': ['Stein-Säckingen', true],
  'STSA': ['St-Saphorin', true],
  'STST': ['St. Stephan', true],
  'STTF': ['Sternen bei Teufen', true],
  'STTL': ['Stettlen', true],
  'STU': ['Studen BE', true],
  'STUA': ['Studen Auto', false],
  'STVI': ['St-Triphon-Village', true],
  'SU': ['St-Ursanne', true],
  'SUB': ['Suberg-Grossaffoltern', true],
  'SUCH': ['Genolier Sus-Châtel', true],
  'SUCU': ['Sumvitg-Cumpadials', true],
  'SUGI': ['Sugiez', true],
  'SUGN': ['Sugnens', true],
  'SUHM': ['Suhr Migros', false],
  'SUHR': ['Suhr', true],
  'SURA': ['Surava', true],
  'SURB': ['St. Urban', true],
  'SURO': ['Surovas', true],
  'SUS': ['Susch', true],
  'SUTZ': ['Sutz', true],
  'SV': ['Sonvilier', true],
  'SW': ['Solothurn West', true],
  'SWB': ['Schwäbis', true],
  'SWD': ['Schwendi bei Heiden', true],
  'SWDG': ['Schwendi bei Grindelwald', true],
  'SWG': ['Sumiswald-Grünen', true],
  'SY': ['Satigny', true],
  'TA': ['Tavannes', true],
  'TABR': ['Tavanasa-Breil/Brigels', true],
  'TAEG': ['Tägerwilen-Gottlieben', true],
  'TAEM': ['Tägerwilen Dorf', true],
  'TAEN': ['Tägerschen', true],
  'TAES': ['Täsch', true],
  'TAEU': ['Täuffelen', true],
  'TAN': ['Tannay', true],
  'TAV': ['Taverne-Torricella', true],
  'TD': ['Tann-Dürnten', true],
  'TDT': ['La Tour-de-Trême Ronclina', true],
  'TEGN': ['Tegna', true],
  'TEN': ['Tenero', true],
  'TER': ['Territet', true],
  'TEU': ['Teufenthal AG', true],
  'TEUF': ['Teufen AR', true],
  'TG': ['Turgi', true],
  'TH': ['Thun', true],
  'THA': ['Thayngen', true],
  'THB': ['Thun GB', false],
  'THBU': ['Thalbrücke', true],
  'THO': ['Thörishaus Station', true],
  'THOD': ['Thörishaus Dorf', true],
  'THS': ['Thusis', true],
  'THU': ['Thurnen', true],
  'TI': ['Tägertschi', true],
  'TICA': ['Tiefencastel', true],
  'TINE': ['La Tine', true],
  'TK': ['Tecknau', true],
  'TKLL': ['Léchelles Tanklager (embr)', false],
  'TLH': ['Thalheim-Altikon', true],
  'TO': ['Toffen', true],
  'TOA': ['Tobel-Affeltrangen', true],
  'TOUR': ['La Tour-de-Peilz', true],
  'TOUV': ['La Tour-de-Trême', true],
  'TR': ['Travers', true],
  'TRAM': ['Tramelan', true],
  'TRCH': ['Tramelan-Chalet', true],
  'TRDE': ['Tramelan-Dessous', true],
  'TRED': ['Trélex dépôt', true],
  'TREL': ['Trélex', true],
  'TRET': ['Le Trétien', true],
  'TRHA': ['Trasadingen', true],
  'TRI': ['Trimbach', true],
  'TRIB': ['Triboltingen', true],
  'TRIN': ['Trin', true],
  'TRIS': ['Trimmis', false],
  'TRLI': ['Zürich Triemli', true],
  'TRO': ['Trogen', true],
  'TROI': ['Troistorrents', true],
  'TRUB': ['Trübbach', true],
  'TRUN': ['Trun', true],
  'TRW': ['Triengen-Winikon', false],
  'TSCH': ['Trubschachen', true],
  'TSSE': ['Tschamut-Selva', true],
  'TU': ['Turbenthal', true],
  'TUE': ['Tüscherz', true],
  'TUI': ['Les Tuileries', true],
  'TUIE': ['Tuilerie', true],
  'TUR': ['Turtmann', true],
  'TUS': ['Tusinge', true],
  'TW': ['Thalwil', true],
  'TWN': ['Twann', true],
  'UE': ['Uetendorf', true],
  'UEA': ['Uetendorf Allmend', true],
  'UEBE': ['Uetliberg', true],
  'UER': ['Uerikon', true],
  'UET': ['Uetikon', true],
  'UIWA': ['Uitikon Waldegg', true],
  'UKU': ['Unterkulm', true],
  'UKUN': ['Unterkulm Nord', true],
  'ULR': ['Ulrichen', true],
  'UNOB': ['Unterentfelden Oberdorf', true],
  'UNPO': ['Unterentfelden Post', true],
  'UNT': ['Unterterzen', true],
  'UNZO': ['Unterzollikofen', true],
  'UPRI': ['Union-Prilly', true],
  'UR': ['Urnäsch', true],
  'URD': ['Urdorf', true],
  'URDW': ['Urdorf Weihermatt', true],
  'URTN': ['Urtenen', true],
  'UST': ['Uster', true],
  'UT': ['Utzenstorf', true],
  'UTI': ['Uttigen', true],
  'UTW': ['Uttwil', true],
  'UVAZ': ['Untervaz-Trimmis', true],
  'UZ': ['Uznach', true],
  'UZW': ['Uzwil', true],
  'VAL': ['Vallorbe', true],
  'VALF': ['Vallorbe-Frontière', false],
  'VALI': ['Val-d\'Illiez', true],
  'VASA': ['Valendas-Sagogn', true],
  'VASM': ['Valeyres-sous-Montagny', true],
  'VAU': ['Vaumarcus', true],
  'VAUL': ['Vaulruz-Nord', true],
  'VAUS': ['Vaulruz-Sud', true],
  'VD': ['Vauderens', true],
  'VECA': ['Vernand-Camarès', true],
  'VECH': ['Vechigen', true],
  'VEGL': ['Vers-l\'Eglise', true],
  'VEMC': ['Vernayaz MC', true],
  'VEMO': ['Versmont', true],
  'VEND': ['Vendlincourt', true],
  'VER': ['Les Verrières', false],
  'VERC': ['Verschiez', true],
  'VERD': ['Verdasio', true],
  'VERF': ['Les Verrières-Frontière', false],
  'VERI': ['La Verrerie', true],
  'VERN': ['Vernayaz', true],
  'VESA': ['Versam-Safien', true],
  'VESC': ['Verscio', true],
  'VEY': ['Veytaux-Chillon', true],
  'VG': ['Villars-sur-Glâne', true],
  'VI': ['Visp', true],
  'VIAB': ['Villars-Bozon', true],
  'VIAR': ['Villars-sur-Ollon', true],
  'VIGO': ['Villars-sur-Ollon Golf', true],
  'VIL': ['Villeneuve VD', true],
  'VIO': ['Vionnaz', true],
  'VM': ['Meyrin', true],
  'VMC': ['Vernier-Meyrin Cargo', false],
  'VOEG': ['Vögelinsegg', true],
  'VOU': ['Vouvry', true],
  'VSX': ['Versoix', true],
  'VT': ['Villeret', true],
  'VTE': ['Villette VD', true],
  'VU': ['Vufflens-la-Ville', true],
  'VUA': ['Vuadens-Sud', true],
  'VUAP': ['La Vuarpillière', true],
  'VUAR': ['Vuarennes', true],
  'VUF': ['Vufflens-le-Château', true],
  'VUIB': ['Vuiteboeuf', true],
  'VV': ['Vevey', true],
  'VVFU': ['Vevey-Funi', true],
  'VVVI': ['Vevey Vignerons', true],
  'VY': ['Villy', true],
  'VZ': ['Villaz-St-Pierre', true],
  'W': ['Winterthur', true],
  'WA': ['Wattwil', true],
  'WAA': ['Wangen an der Aare', true],
  'WAB': ['Waldibrücke', true],
  'WAE': ['Wädenswil', true],
  'WAEN': ['Wängi', true],
  'WAIE': ['Wasen i.E.', true],
  'WAL': ['Walenstadt', true],
  'WALG': ['Waldburg', true],
  'WALK': ['Walkringen', true],
  'WALS': ['Waltenschwil', false],
  'WALZ': ['Walzenhausen', true],
  'WARS': ['Wartensee', true],
  'WAS': ['Wassen', false],
  'WASS': ['Wasserauen', true],
  'WAST': ['Walterswil-Striegel', true],
  'WAU': ['Wauwil', true],
  'WAVU': ['Waltensburg/Vuorz', true],
  'WB': ['Worb SBB', true],
  'WBA': ['Weissenbach', true],
  'WBB': ['Wabern bei Bern', true],
  'WBG': ['Warmesberg', true],
  'WBL': ['Worblaufen', true],
  'WBOL': ['Wangen bei Olten', true],
  'WCH': ['Wichtrach', true],
  'WCHO': ['Walchwil Hörndli', true],
  'WCHW': ['Walchwil', true],
  'WD': ['Wiesendangen', true],
  'WE': ['Wettingen', true],
  'WEBM': ['Weberei Matzingen', true],
  'WEGG': ['Winteregg', true],
  'WEIS': ['Weissbad', true],
  'WEN': ['Wengi', false],
  'WF': ['Weinfelden', true],
  'WFKV': ['Weinfelden KVA Thurgau (Abzw)', false],
  'WFS': ['Weinfelden Süd', false],
  'WG': ['Weissenburg', true],
  'WGR': ['Winterthur Grüze', true],
  'WH': ['Wolhusen', true],
  'WHE': ['Winterthur Hegi', true],
  'WHW': ['Wolhusen Weid', true],
  'WI': ['Wildegg', true],
  'WIED': ['Wiedlisbach', true],
  'WIES': ['Davos Wiesen', true],
  'WIG': ['Wiggen', false],
  'WIGR': ['Wiesengrund', true],
  'WIHA': ['Wilchingen-Hallau', true],
  'WIL': ['Wil SG', true],
  'WILA': ['Wila', true],
  'WILD': ['Wilderswil', true],
  'WILE': ['Herisau Wilen', true],
  'WILN': ['Wilen bei Wollerau', true],
  'WILO': ['Wil Ost', false],
  'WIN': ['Winkel am Zürichsee', true],
  'WIT': ['Wittenbach', true],
  'WITO': ['Wienacht-Tobel', true],
  'WK': ['Weiach-Kaiserstuhl', false],
  'WKD': ['Wankdorf (Abzw)', false],
  'WL': ['Wald ZH', true],
  'WLTK': ['Waltikon', true],
  'WM': ['Wimmis', true],
  'WN': ['Weesen', false],
  'WO': ['Wohlen AG', true],
  'WOBO': ['Worbboden', true],
  'WOFU': ['Wohlen Fulenbach', true],
  'WOL': ['Wollerau', true],
  'WOOB': ['Wohlen Oberdorf', true],
  'WOS': ['Wolfenschiessen', true],
  'WP': ['Wildpark-Höfli', true],
  'WR': ['Wiler', true],
  'WS': ['Wallisellen', true],
  'WSAU': ['Willisau', true],
  'WSEE': ['Winterthur Seen', true],
  'WST': ['Werthenstein', true],
  'WSTA': ['Waldstatt', true],
  'WTOE': ['Winterthur Töss', true],
  'WUE': ['Wünnewil', true],
  'WUER': ['Würenlos', true],
  'WWAL': ['Winterthur Wallrüti', true],
  'WWE': ['Winterthur West (Abzw)', false],
  'WWUE': ['Winterthur Wülflingen', true],
  'WY': ['Wynigen', true],
  'WZ': ['Wetzikon ZH', true],
  'YENS': ['Yens', true],
  'YND': ['Yvonand', true],
  'YV': ['Yverdon-les-Bains', true],
  'YVWB': ['Yverdon William Barbey', true],
  'ZAE': ['Zäziwil', true],
  'ZAF': ['Zürich Affoltern', true],
  'ZALT': ['Zizers Altlöser', false],
  'ZAS': ['Zürich Altstetten', true],
  'ZB': ['Ziegelbrücke', true],
  'ZBR': ['Zihlbrücke', true],
  'ZBRU': ['Zürich Brunau', true],
  'ZBZ': ['Zürich Binz', true],
  'ZELL': ['Zell LU', true],
  'ZEN': ['Zürich Enge', true],
  'ZERM': ['Zermatt', true],
  'ZETZ': ['Zetzwil', true],
  'ZEZ': ['Zernez', true],
  'ZF': ['Zofingen', true],
  'ZFFR': ['Frauenfeld Zuckerrüben', false],
  'ZFH': ['Zürich Flughafen', true],
  'ZG': ['Zug', true],
  'ZGCA': ['Zug Casino', true],
  'ZGFR': ['Zug Fridbach', true],
  'ZGH': ['Zürich Giesshübel', true],
  'ZGO': ['Zug Oberwil', true],
  'ZGPP': ['Zug Postplatz', true],
  'ZGSE': ['Zug Schutzengel', true],
  'ZGUB': ['Zürich Gubrist', false],
  'ZHDB': ['Zürich Hardbrücke', true],
  'ZHER': ['Zürich Herdern Abstellgruppe', false],
  'ZIE': ['St. Urban Ziegelei', true],
  'ZIM': ['Zimeysa', true],
  'ZIZ': ['Zizers', true],
  'ZIZS': ['Zizers SBB', false],
  'ZK': ['Zollikon', true],
  'ZKBG': ['Zollikerberg', true],
  'ZLE': ['Zürich Leimbach', true],
  'ZMA': ['Zürich Manegg', true],
  'ZMUE': ['Zürich Mülligen', false],
  'ZO': ['Zollbrück', true],
  'ZOER': ['Zürich Oerlikon', true],
  'ZOL': ['Zollikofen', true],
  'ZOLW': ['Zollikofen West (Spw)', false],
  'ZOO': ['Crémines-Zoo', true],
  'ZSAA': ['Zürich Saalsporthalle', true],
  'ZSEB': ['Zürich Seebach', true],
  'ZSEL': ['Zürich Selnau', true],
  'ZSTH': ['Zürich Stadelhofen', true],
  'ZTB': ['Zürich Tiefenbrunnen', true],
  'ZUE': ['Zürich HB', true],
  'ZUEM': ['Zürchersmühle', true],
  'ZUER': ['Zürich Rehalp', true],
  'ZUFH': ['Zufikon Hammergut', true],
  'ZUFI': ['Zufikon', true],
  'ZUM': ['Zumikon', true],
  'ZUOZ': ['Zuoz', true],
  'ZUSZ': ['Zürich HB SZU', true],
  'ZVB': ['Zürich Vorbahnhof', false],
  'ZVBS': ['Zürich Vorbahnhof Süd', false],
  'ZVBW': ['Zürich Vorbahnhof West', false],
  'ZW': ['Zweisimmen', true],
  'ZWBR': ['Zweibrücken', true],
  'ZWD': ['Zweidlen', true],
  'ZWEI': ['Zweilütschinen', true],
  'ZWG': ['Zwingen', true],
  'ZWIE': ['Zürich Wiedikon', true],
  'ZWIP': ['Zürich Wipkingen', true],
  'ZWOL': ['Zürich Wollishofen', true],
  'ZZ': ['Bad Zurzach', true],
};
